<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.4.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Achal Neupane">

  
  
  
    
  
  <meta name="description" content="Statistics series">

  
  <link rel="alternate" hreflang="en-us" href="/achalneupane.github.io/post/stat_601_final/">

  


  

  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/achalneupane.github.io/css/academic.min.c66516cf97186fe7fa872ca1f0e4401a.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-145752794-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/achalneupane.github.io/index.webmanifest">
  <link rel="icon" type="image/png" href="/achalneupane.github.io/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/achalneupane.github.io/img/icon-192.png">

  <link rel="canonical" href="/achalneupane.github.io/post/stat_601_final/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@achalneupane">
  <meta property="twitter:creator" content="@achalneupane">
  
  <meta property="og:site_name" content="Achal Neupane">
  <meta property="og:url" content="/achalneupane.github.io/post/stat_601_final/">
  <meta property="og:title" content="STAT_601_Final | Achal Neupane">
  <meta property="og:description" content="Statistics series"><meta property="og:image" content="/achalneupane.github.io/img/icon-192.png">
  <meta property="twitter:image" content="/achalneupane.github.io/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2019-11-18T17:26:23-05:00">
    
    <meta property="article:modified_time" content="2019-11-18T17:26:23-05:00">
  

  


  





  <title>STAT_601_Final | Achal Neupane</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/achalneupane.github.io/">Achal Neupane</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#impact"><span>Impact</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#contact"><span>Contact</span></a>
        </li>

        
        

      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article" itemscope itemtype="http://schema.org/Article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1 itemprop="name">STAT_601_Final</h1>

  

  
    



<meta content="2019-11-18 17:26:23 -0500 -0500" itemprop="datePublished">
<meta content="2019-11-18 17:26:23 -0500 -0500" itemprop="dateModified">

<div class="article-metadata">

  
  
  
  
  <div>
    



  <span itemprop="author name" itemtype="http://schema.org/Person"><a href="/achalneupane.github.io/authors/achal-neupane/"><strong>Achal Neupane</strong></a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
    
    <time>Nov 18, 2019</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    22 min read
  </span>
  

  
  
  

  
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/achalneupane.github.io/post/stat_601_final/&amp;text=STAT_601_Final" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/achalneupane.github.io/post/stat_601_final/&amp;t=STAT_601_Final" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=STAT_601_Final&amp;body=/achalneupane.github.io/post/stat_601_final/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/achalneupane.github.io/post/stat_601_final/&amp;title=STAT_601_Final" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=STAT_601_Final%20/achalneupane.github.io/post/stat_601_final/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/achalneupane.github.io/post/stat_601_final/&amp;title=STAT_601_Final" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<p>Final Projects (Fall 2019)- Statistics 601. Due on December 18, 2019 at 5 pm central time.</p>
<p>Work on this exam by yourself and be sure to reference any material you use on your exam. Only discuss the exam with me, Ms. Fuglsby, or Ms. Hajebi and not the other students in the class.
Do two of the following three problems. Turn in one pdf and RMD file for each problem clearly labeling which problems you have chosen to do.
1: The data shown in schizophrenia.csv were collected in a follow-up study of women patients with schizophrenia and summarized in Davis (2002), Statistical Methods for the Analysis of Repeated Measurements, Springer, New York. The binary response recorded at 0, 2, 6, 8 and 10 months after hospitalization was thought disorder (absent or present). The single covariate is the factor indicating whether a patient had suffered early or late onset of her condition (age of onset less than 20 years or age of onset 20 years or above). The question of interest is whether the course of the illness differs between patients with early and late onset? Investigate the question of interest.
i) Provide a two to three-page write-up (including graphs) explaining your analysis of the experiment and the conclusions you can draw from it.<br />
ii) As a secondary component provide annotated code that replicates your analysis.
Make sure to discuss any concerns about the modeling assumptions used in your analysis.
The .csv file has the following variables.
subject
- the patient ID, a factor with levels 1 to 44.
onset
- the time of onset of the disease, a factor with levels &lt; 20 yrs and &gt; 20 yrs.
disorder
- whether thought disorder was absent or present, the response variable.
month
- month after hospitalization.</p>
<p>Please note that you may have already explored this dataset in the class. Even so, please do a complete and extended analysis answering the questions, with the focus of writing and explaining the what you have found in your analysis.</p>
<p>For this analysis, first I splitted the schizophrenia data into younger and older patients percentage.</p>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>schizophrenia2 &lt;- read.csv(&quot;https://raw.githubusercontent.com/achalneupane/data/master/schizophrenia.csv&quot;, header = TRUE, sep =&quot;,&quot;)

cat(&quot;Calculating percentage data&quot;)</code></pre>
<pre><code>## Calculating percentage data</code></pre>
<pre class="r"><code>younger_percentage &lt;- c( nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 0 &amp; disorder == &quot;present&quot;))) / 
                           nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 0))),
                         nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 2 &amp; disorder == &quot;present&quot;))) / 
                           nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 2))),
                         nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 6 &amp; disorder == &quot;present&quot;))) / 
                           nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 6))),
                         nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 8 &amp; disorder == &quot;present&quot;))) / 
                           nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 8))),
                         nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 10 &amp; disorder == &quot;present&quot;))) / 
                           nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 10))))

older_percentage &lt;- c( nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 0 &amp; disorder == &quot;present&quot;))) / 
                         nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 0))),
                       nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 2 &amp; disorder == &quot;present&quot;))) / 
                         nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 2))),
                       nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 6 &amp; disorder == &quot;present&quot;))) / 
                         nrow(subset(schizophrenia2, (onset == &quot;&lt; 20 yrs&quot; &amp; month == 6))),
                       nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 8 &amp; disorder == &quot;present&quot;))) / 
                         nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 8))),
                       nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 10 &amp; disorder == &quot;present&quot;))) / 
                         nrow(subset(schizophrenia2, (onset == &quot;&gt; 20 yrs&quot; &amp; month == 10))))

younger_percentage %&gt;% summary() %&gt;% as.matrix() %&gt;% t() %&gt;% knitr::kable(caption = &quot;Summary statistics for presence of younger onset data&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-1">Table 1: </span>Summary statistics for presence of younger onset data</caption>
<thead>
<tr class="header">
<th align="right">Min.</th>
<th align="right">1st Qu.</th>
<th align="right">Median</th>
<th align="right">Mean</th>
<th align="right">3rd Qu.</th>
<th align="right">Max.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.09375</td>
<td align="right">0.15625</td>
<td align="right">0.25</td>
<td align="right">0.34375</td>
<td align="right">0.59375</td>
<td align="right">0.625</td>
</tr>
</tbody>
</table>
<pre class="r"><code>older_percentage %&gt;% summary() %&gt;% as.matrix() %&gt;% t() %&gt;% knitr::kable(caption = &quot;Summary statistics for presence of older onset data&quot;)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-1">Table 1: </span>Summary statistics for presence of older onset data</caption>
<thead>
<tr class="header">
<th align="right">Min.</th>
<th align="right">1st Qu.</th>
<th align="right">Median</th>
<th align="right">Mean</th>
<th align="right">3rd Qu.</th>
<th align="right">Max.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">0.0833333</td>
<td align="right">0.09375</td>
<td align="right">0.2520833</td>
<td align="right">0.5</td>
<td align="right">0.5833333</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot(x = seq(1:5), y=younger_percentage, type=&quot;l&quot;, col=1, xaxt=&quot;n&quot;, ylim=c(0,0.8),
     xlab=&quot;Months&quot;, ylab=&quot;Percent present&quot;, main = &quot;Percent present by age at Onset&quot;)
lines(older_percentage, col=4)
legend(&quot;topright&quot;, legend=c(&quot;Percent present at Onset &lt; 20 years&quot;, &quot;Percent Present at Onset &gt; 20 years&quot;), 
       col=   c(&quot;1&quot;, &quot;4&quot;), lty = c(1, 1))
axis(side=1, at=seq(1:5), labels = c(0, 2, 6, 8, 10))
axis(side=2, at=seq(1:11), labels = c(0, 0.1, .2, .3, .4, .5, .6, .7, .8, .9, 1))</code></pre>
<p><img src="/achalneupane.github.io/post/Stat_601_FINAL_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>From this analysis, we see that for the older-onset population, the mean and the median of the percentage of <code>presence of schizophrenia</code> are lower. Looking at the percentage plot, it appears that at each sample date (in months) the percentage is lower in the older-onset population.
Looking at the graph of the precentages, it looks like the precentage is lower in the older-onset popullation at every sample date (in months). Both of these seem to indicate that the question is worth investigating more closely.
The mosaic plot shows an increase of ‘absence’ for both populations, through 8 months. Then, a light diminishing of absences at 10 months.</p>
<p>We can then use GEE approach to further investigate the data.</p>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## Loading required package: grid</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 2: </span>QIC from GEE Independent (identity)</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>QIC</td>
<td align="right">163.7889</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 2: </span>QIC from GEE Exchangeable</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>QIC</td>
<td align="right">163.6867</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 2: </span>QIC from GEE Unstructured</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>QIC</td>
<td align="right">164.011</td>
</tr>
</tbody>
</table>
<p>In exchangeable and unstructured model, the QIC score is the lowest. So for the selection of model, either model can be a good choice. However, comparing parameters such as CIC, QICu and QICC, I think the exchangeable model seems better.</p>
<p>Additionally, we can also use linear mixed effects model (lmer) and develop different models by selecting different variables, and then compare our models.</p>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, :
## Model failed to converge with max|grad| = 0.00345048 (tol = 0.002, component 1)</code></pre>
<pre><code>## [1] &quot;Without interaction term:&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Fixed Slope :  179.591302394191&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Random Slope:  184.624563351416&quot;</code></pre>
<pre><code>## [1] &quot;With interaction term: month v. onset:&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Fixed Slope :  184.587333241198&quot;</code></pre>
<pre><code>## [1] &quot;BIC: Random Slope:  189.620892549092&quot;</code></pre>
<p>To see whether which models works best in our case, we can do model comparison with ANOVA.</p>
<pre><code>## Fixed Slope v. Random Slope (no intaction term)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Chi Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>schiz_lmer1</td>
<td align="right">6</td>
<td align="right">161.1403</td>
<td align="right">179.5913</td>
<td align="right">-74.57013</td>
<td align="right">149.1403</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td>schiz_lmer2</td>
<td align="right">8</td>
<td align="right">160.0232</td>
<td align="right">184.6246</td>
<td align="right">-72.01159</td>
<td align="right">144.0232</td>
<td align="right">5.117087</td>
<td align="right">2</td>
<td align="right">0.0774174</td>
</tr>
</tbody>
</table>
<pre><code>## Interaction Term v. No Interaction Term (fixed slope)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Chi Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>schiz_lmer1</td>
<td align="right">6</td>
<td align="right">161.1403</td>
<td align="right">179.5913</td>
<td align="right">-74.57013</td>
<td align="right">149.1403</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td>schiz_lmer3</td>
<td align="right">7</td>
<td align="right">163.0611</td>
<td align="right">184.5873</td>
<td align="right">-74.53056</td>
<td align="right">149.0611</td>
<td align="right">0.079143</td>
<td align="right">1</td>
<td align="right">0.7784622</td>
</tr>
</tbody>
</table>
<pre><code>## Fixed Slope, No interaction Term v. Random Slope, With interaction term</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Chi Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>schiz_lmer1</td>
<td align="right">6</td>
<td align="right">161.1403</td>
<td align="right">179.5913</td>
<td align="right">-74.57013</td>
<td align="right">149.1403</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td>schiz_lmer4</td>
<td align="right">9</td>
<td align="right">161.9443</td>
<td align="right">189.6209</td>
<td align="right">-71.97216</td>
<td align="right">143.9443</td>
<td align="right">5.195931</td>
<td align="right">3</td>
<td align="right">0.1579996</td>
</tr>
</tbody>
</table>
<pre><code>## Random Slope, No interaction term v. Fixed Slope, With interaction term</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Chi Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>schiz_lmer3</td>
<td align="right">7</td>
<td align="right">163.0611</td>
<td align="right">184.5873</td>
<td align="right">-74.53056</td>
<td align="right">149.0611</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td>schiz_lmer2</td>
<td align="right">8</td>
<td align="right">160.0232</td>
<td align="right">184.6246</td>
<td align="right">-72.01159</td>
<td align="right">144.0232</td>
<td align="right">5.037944</td>
<td align="right">1</td>
<td align="right">0.0247979</td>
</tr>
</tbody>
</table>
<pre><code>## No interaction term v. Interaction term (random slope)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Chi Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>schiz_lmer2</td>
<td align="right">8</td>
<td align="right">160.0232</td>
<td align="right">184.6246</td>
<td align="right">-72.01159</td>
<td align="right">144.0232</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td>schiz_lmer4</td>
<td align="right">9</td>
<td align="right">161.9443</td>
<td align="right">189.6209</td>
<td align="right">-71.97216</td>
<td align="right">143.9443</td>
<td align="right">0.0788446</td>
<td align="right">1</td>
<td align="right">0.7788693</td>
</tr>
</tbody>
</table>
<pre><code>## Fixed Slope v. Random Slope (with intaction term)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">logLik</th>
<th align="right">deviance</th>
<th align="right">Chisq</th>
<th align="right">Chi Df</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>schiz_lmer3</td>
<td align="right">7</td>
<td align="right">163.0611</td>
<td align="right">184.5873</td>
<td align="right">-74.53056</td>
<td align="right">149.0611</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td>schiz_lmer4</td>
<td align="right">9</td>
<td align="right">161.9443</td>
<td align="right">189.6209</td>
<td align="right">-71.97216</td>
<td align="right">143.9443</td>
<td align="right">5.116788</td>
<td align="right">2</td>
<td align="right">0.077429</td>
</tr>
</tbody>
</table>
<p>The model with a fixed effect and no interaction term has the lowest BIC score. This would be an indicator that the concept of contact is not likely to add much to the template if anything. The most significant difference based on ANOVA analysis is between random slope, no interaction term and fixed slope, with interaction term (fourth table). This is indicated with a p-score of 0.025 i.e., [P&lt;0.05].</p>
<ol start="2" style="list-style-type: decimal">
<li>(Vole Data)- Consider the “microtus” dataset in the “Flury” library in R.
Background from Airoldi_Flury_Salvioni_JTheorBiol_1995: Discrimination Between Two Species of Microtus using both Classified and Unclassified Observations.
“1. Introduction
Microtus subterraneus and M. multiplex are now considered to be two distinct species (Niethammer, 1982; Krapp, 1982), contrary to the older view of Ellerman &amp; Morrison-Scott (1951). The two species differ in the number of chromosomes: 2n=52 or 54 for M. subterraneus, and 2n=46 or 48 for M. multiplex. Hybrids from the laboratory have reduced fertility (Meylan, 1972), and hybrids from the field, whose karyotypes would be clearly recognizable, have never been found (Krapp, 1982).
The geographic ranges of distribution of M. subterraneus and M. multiplex overlap to some extent in the Alps of southern Switzerland and northern Italy (Niethammer, 1982; Krapp, 1982). M. subterraneus is smaller than M. multiplex in most measurements, and occurs at elevations from 1000 m to over 2000 m, except in the western part of its range (for example, Belgium and Brittany), where it is found in lower elevations. M. multiplex is found at similar elevations, but also at altitudes from 200–300 m south of the Alps (Ticino, Toscana).
The two chromosomal types of M. subterraneus can be crossed in the laboratory (Meylan, 1970, 1972), but no hybrids have so far been found in the field. In M. multiplex, the two chromosomal types show a distinct distribution range, but they are morphologically indistinguishable, and a hybrid has been found in the field (Storch &amp; Winking, 1977).
No reliable criteria based on cranial morphology have been found to distinguish the two species. Saint Girons (1971) pointed out a difference in the sutures of the posterior parts of the premaxillary and nasal bones compared to the frontal one, but this criterion does not work well in many cases. For both paleontological and biogeographical research it would be useful to have a good rule for discriminating between the two species, because much of the data available are in form of skull remains, either fossilized or from owl pellets.
The present study was initiated by a data collection consisting of eight morphometric variables measured by one of the authors (Salvioni) using a Nikon measure-scope (accuracy 1/1000 mm) and dial calipers (accuracy 1/100 mm). The sample consists of 288 specimens collected mostly in Central Europe (Alps and Jura mountains) and in Toscana. One peculiar aspect of this data set is that the chromosomes of 89 specimens were analyzed to identify the species. Only the morphometric characteristics are available for the remaining 199 specimens…”</li>
</ol>
<p>Develop a model from the 89 specimens that you can use to predict the group membership of the remaining 199 specimens’.
a) Explain your GLM and assess the quality of the fit with the classified observations.<br />
You may want to use Cross Validation to predict the accuracy of your model.
b) Provide a two to three-page write-up (including graphs) explaining your analysis of the dataset and your recommendations on the usefulness of your predictions.
c) Provide predictions for the unclassified observations.<br />
d) As a secondary component provide annotated code that replicates your analysis.</p>
<p>The microtus data set for this final contains 288 observations. Only 89 of these obs are classified as either Subterraneus or Multiplex. The other 199 obs are unknown. The data set has 8 variables that are all measurements of the two possible species. The objective of this final project will be to predict the species of the unknown obs by modeling the 89 classified obs.</p>
<p>The microtus dataset for this final assignement has 288 rows and 9 columns. We are using 89 of these observations which are labeled as either Subterraneus or Multiplex and the rest of the 199 observartions are unknown. We are splitting our data into known and unknown groups for prediction purposes.</p>
<pre><code>## Loading required package: tools</code></pre>
<pre><code>## 
## Attaching package: &#39;HSAUR2&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     schizophrenia2</code></pre>
<pre><code>## 
## Attaching package: &#39;HSAUR&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     schizophrenia2</code></pre>
<pre><code>## The following objects are masked from &#39;package:HSAUR2&#39;:
## 
##     agefat, aspirin, BtheB, gardenflowers, GHQ, HSAURtable, mastectomy,
##     polyps3, pottery, respiratory, schooldays, womensrole</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<pre><code>## Loading required package: splines</code></pre>
<pre><code>## Loading required package: RcmdrMisc</code></pre>
<pre><code>## Loading required package: car</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## Loading required package: sandwich</code></pre>
<pre><code>## Loading required package: effects</code></pre>
<pre><code>## lattice theme set by effectsTheme()
## See ?effectsTheme for details.</code></pre>
<pre><code>## The Commander GUI is launched only in interactive sessions</code></pre>
<pre><code>## Type &#39;citation(&quot;pROC&quot;)&#39; for a citation.</code></pre>
<pre><code>## 
## Attaching package: &#39;pROC&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     cov, smooth, var</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## 
## Attaching package: &#39;GGally&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     nasa</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/achalneupane.github.io/post/Stat_601_FINAL_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>First, we check the relationship between the variables in our data using ggpairs plot where different classes are shown in different colours. Based on this plot (looking at the lower left points), we can say that the all of these variables are somewhat correlated which can be confirmed by their corresponding values in the upper right. Another interesting aspect of this plot is the density distribution which shows us the distribution of suberraneus, multiplex and the unknown groups, and also whether the variables shown here appear similar or different.</p>
<pre class="r"><code># ############################
# Now we do logistic regression of our Model followed by AIC and p value checking


model=glm(Group~M1Left+Height+Foramen,data=known,family=binomial)
AIC(model)</code></pre>
<pre><code>## [1] 29.09982</code></pre>
<pre class="r"><code>summary(model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Group ~ M1Left + Height + Foramen, family = binomial, 
##     data = known)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.20430  -0.01969   0.01008   0.10191   1.24456  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) 80.578764  31.313670   2.573  0.01007 * 
## M1Left      -0.042164   0.014111  -2.988  0.00281 **
## Height      -0.026826   0.028312  -0.948  0.34336   
## Foramen      0.004990   0.003317   1.504  0.13253   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 123.28  on 88  degrees of freedom
## Residual deviance:  21.10  on 85  degrees of freedom
## AIC: 29.1
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<pre class="r"><code># MSE of the model
MSE.glm &lt;- mean((predict(model, newdata = known, type = &quot;response&quot;)-known$Group)^2)
MSE.glm</code></pre>
<pre><code>## [1] 0.03622752</code></pre>
<pre class="r"><code>cat(&quot;Cross validation with 10 fold: &quot;)</code></pre>
<pre><code>## Cross validation with 10 fold:</code></pre>
<pre class="r"><code>library(boot)</code></pre>
<pre><code>## 
## Attaching package: &#39;boot&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     logit</code></pre>
<pre class="r"><code>(cv.err.10 &lt;- mean(cv.glm(known, model, K = 10)$delta))</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## [1] 0.04652552</code></pre>
<p>My logistic regression model (GLM) with formula <code>Group~M1Left+Height+Foramen</code> has an MSE(Mean square error) of 0.036 which was quite similar to the error values by Cross validation with 10 fold (0.051). The AIC calculated for this model was 29.09982. I then used stepwise regression below to enquire whether this model(and variables in the model) was the best model I could choose from.</p>
<p>Now, we can also construct the classification tree by selecting all variables.</p>
<pre class="r"><code>library(rpart)
library(party)</code></pre>
<pre><code>## Loading required package: mvtnorm</code></pre>
<pre><code>## Loading required package: modeltools</code></pre>
<pre><code>## Loading required package: stats4</code></pre>
<pre><code>## 
## Attaching package: &#39;modeltools&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     Predict</code></pre>
<pre><code>## The following object is masked from &#39;package:lme4&#39;:
## 
##     refit</code></pre>
<pre><code>## Loading required package: strucchange</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code># library(caret)
# model &lt;- train(
#   factor(Group) ~., data = known, method = &quot;ctree2&quot;,
#   trControl = trainControl(&quot;cv&quot;, number = 10),
#   tuneGrid = expand.grid(maxdepth = 3, mincriterion = 0.95 )
#   )
# 
# plot(model$finalModel)

p1.1.tree &lt;- rpart(Group~.,data=known,control = rpart.control( minsplit = 10))

library(party)
library(partykit)</code></pre>
<pre><code>## Loading required package: libcoin</code></pre>
<pre><code>## 
## Attaching package: &#39;partykit&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:party&#39;:
## 
##     cforest, ctree, ctree_control, edge_simple, mob, mob_control,
##     node_barplot, node_bivplot, node_boxplot, node_inner, node_surv,
##     node_terminal, varimp</code></pre>
<pre class="r"><code>plot(as.party(p1.1.tree),
     tp_args = list(id = FALSE))</code></pre>
<p><img src="/achalneupane.github.io/post/Stat_601_FINAL_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code># # Make predictions on the test data
# library(dplyr)
# predicted.classes &lt;- model %&gt;% predict(uk)</code></pre>
<p>In above figure, using a tree, I want to see what variables are being chosen. These results seemed to follow along with the summary results from the model seleted below with step regression which is why the step model seems better than my GLM above.</p>
<pre class="r"><code>require(randomForest)</code></pre>
<pre><code>## Loading required package: randomForest</code></pre>
<pre><code>## randomForest 4.6-14</code></pre>
<pre><code>## Type rfNews() to see new features/changes/bug fixes.</code></pre>
<pre><code>## 
## Attaching package: &#39;randomForest&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     margin</code></pre>
<pre><code>## The following object is masked from &#39;package:MuMIn&#39;:
## 
##     importance</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine</code></pre>
<pre class="r"><code>fit=randomForest(factor(Group)~.,data=known)
varImpPlot(fit)</code></pre>
<p><img src="/achalneupane.github.io/post/Stat_601_FINAL_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Here, based on random forest model, I want to see what variables are being chosen. Based on this, Foramen seems to be the least iportant while M1left seems to the most important variables. Here, Mean DecreaseinGini is the average (mean) of a variable’s total decrease in node impurity, weighted by the proportion of samples reaching that node in each individual decision tree in the random forest. A higher Mean Decrease in Gini indicates higher variable importance.</p>
<p>In an attempt to improve selection of variables in my model above, I performed a stepwise selection of all variables. This process determined that the lowest AIC (27.70) was found when using <code>M1Left + M3Left + Foramen + Length + Height</code>. This model indicates that the omission of Foramen and Length as in my original model is not a good idea. Nonetheless the error for this model is even smaller (0.027) than what we had for original model, and with a much improved cross validated error of .048.</p>
<pre class="r"><code>#use stepwise regression for the glm
step_known &lt;- step(glm(Group ~., data = known, family = &quot;binomial&quot;), direction=&quot;both&quot;)</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## Start:  AIC=32.96
## Group ~ M1Left + M2Left + M3Left + Foramen + Pbone + Length + 
##     Height + Rostrum</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>##           Df Deviance    AIC
## - M2Left   1   14.965 30.965
## - Pbone    1   15.288 31.288
## - Rostrum  1   15.627 31.627
## &lt;none&gt;         14.962 32.962
## - Length   1   17.330 33.330
## - Height   1   18.744 34.744
## - Foramen  1   19.434 35.434
## - M3Left   1   20.654 36.654
## - M1Left   1   40.753 56.753</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## 
## Step:  AIC=30.97
## Group ~ M1Left + M3Left + Foramen + Pbone + Length + Height + 
##     Rostrum</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>##           Df Deviance    AIC
## - Pbone    1   15.306 29.306
## - Rostrum  1   15.627 29.627
## &lt;none&gt;         14.965 30.965
## - Length   1   18.268 32.268
## - Height   1   18.945 32.945
## + M2Left   1   14.962 32.962
## - Foramen  1   19.965 33.965
## - M3Left   1   20.763 34.763
## - M1Left   1   42.436 56.436</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## 
## Step:  AIC=29.31
## Group ~ M1Left + M3Left + Foramen + Length + Height + Rostrum</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>##           Df Deviance    AIC
## - Rostrum  1   15.703 27.703
## &lt;none&gt;         15.306 29.306
## - Length   1   18.625 30.625
## - Height   1   18.951 30.951
## + Pbone    1   14.965 30.965
## + M2Left   1   15.288 31.288
## - M3Left   1   20.855 32.855
## - Foramen  1   21.418 33.418
## - M1Left   1   42.970 54.970</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## 
## Step:  AIC=27.7
## Group ~ M1Left + M3Left + Foramen + Length + Height</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>##           Df Deviance    AIC
## &lt;none&gt;         15.703 27.703
## - Length   1   18.960 28.960
## - Height   1   19.019 29.019
## + Rostrum  1   15.306 29.306
## + Pbone    1   15.627 29.627
## + M2Left   1   15.694 29.694
## - M3Left   1   21.039 31.039
## - Foramen  1   21.463 31.463
## - M1Left   1   46.843 56.843</code></pre>
<pre class="r"><code># step_known &lt;- step(glm(Group ~., data = known, family = &quot;binomial&quot;),trace=F, direction=&quot;both&quot;)

#extract the formula with the lowest aic
form_known &lt;- formula(step_known)
form_known</code></pre>
<pre><code>## Group ~ M1Left + M3Left + Foramen + Length + Height</code></pre>
<pre class="r"><code>model_step &lt;- glm(Group ~ M1Left + M3Left + Foramen + Length + Height, data=known,family=binomial)</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre class="r"><code>AIC(model_step)</code></pre>
<pre><code>## [1] 27.70264</code></pre>
<pre class="r"><code>summary(model_step)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Group ~ M1Left + M3Left + Foramen + Length + Height, 
##     family = binomial, data = known)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.26335  -0.00138   0.00013   0.05223   1.14144  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) 187.830585 101.914533   1.843   0.0653 .
## M1Left       -0.058382   0.026760  -2.182   0.0291 *
## M3Left        0.024869   0.016656   1.493   0.1354  
## Foramen       0.011898   0.007164   1.661   0.0968 .
## Length       -0.041467   0.029516  -1.405   0.1600  
## Height       -0.092972   0.071107  -1.307   0.1910  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 123.279  on 88  degrees of freedom
## Residual deviance:  15.703  on 83  degrees of freedom
## AIC: 27.703
## 
## Number of Fisher Scoring iterations: 10</code></pre>
<pre class="r"><code># MSE from step regression best model
MSE.glm_step &lt;- mean((predict(model_step, newdata = known, type = &quot;response&quot;)-known$Group)^2)
MSE.glm_step</code></pre>
<pre><code>## [1] 0.02740134</code></pre>
<pre class="r"><code>cat(&quot;Cross validation with 10 fold: &quot;)</code></pre>
<pre><code>## Cross validation with 10 fold:</code></pre>
<pre class="r"><code>(cv.err_step.10 &lt;- mean(cv.glm(known, model_step, K = 10)$delta))</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## Warning: glm.fit: algorithm did not converge</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred

## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre><code>## [1] 0.06012331</code></pre>
<p>Now finally, the best model that was selected after step regression will be used to predict the rest of the data set that is unclassified (the unknown data: uk). The AIC for this model was 27.70 which is smaller (thus better) than our original model. Also, the MSE for this model was only 0.027 which is smaller (thus better) than our original model. Additionally, the cross validation error was 048 which is a bit higher than our MSE for this model and, but still better than the CV of our orignal model. Anyway, I will be selcting this model with AIC 0.27 from obtained step regression for the prediction purpose.</p>
<p>The specific observation after predictions using the model will be shown below. I will also show a table of count of each species class at the bottom.</p>
<pre class="r"><code>##################################################
# ### ROC curve
# # source: https://thestatsgeek.com/2014/05/05/area-under-the-roc-curve-assessing-discrimination-in-logistic-regression/
# model=glm(Group~M1Left+Height+Foramen, data=known, family=binomial)
# pred=predict(model,data=known, type=&quot;response&quot;)
# (roc(known$Group,pred))$auc ## this gives the area under curve
# plot(roc(known$Group,pred))

#######################
## Final Model
uk=subset(mc,Group==2)
known=subset(mc,Group!=2)

# Using chosen model from stepwise regression
Final_formula=Group~M1Left+M2Left+M3Left+Foramen+Height
model=glm(Final_formula,data=known,family=binomial)</code></pre>
<pre><code>## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
<pre class="r"><code>pred=predict(model,newdata=uk,type=&quot;response&quot;)
summary(model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Final_formula, family = binomial, data = known)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.46039  -0.00606   0.00410   0.09077   1.56483  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) 121.314960  49.465349   2.453  0.01419 * 
## M1Left       -0.049655   0.017862  -2.780  0.00544 **
## M2Left       -0.017500   0.017327  -1.010  0.31251   
## M3Left        0.012076   0.007616   1.586  0.11283   
## Foramen       0.006361   0.003937   1.615  0.10620   
## Height       -0.060146   0.044815  -1.342  0.17957   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 123.279  on 88  degrees of freedom
## Residual deviance:  17.754  on 83  degrees of freedom
## AIC: 29.754
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<pre class="r"><code>for(j in 1:nrow(uk)){
  if(pred[j]&lt;0.5)
  {uk[j,1]=&quot;multiplex&quot;}
  if(pred[j]&gt;=0.5){uk[j,1]=&quot;subterraneous&quot;}
}

cat(&quot;This is the first 6 rows of the predictions for unclassified observations&quot;)</code></pre>
<pre><code>## This is the first 6 rows of the predictions for unclassified observations</code></pre>
<pre class="r"><code>head(uk,6) </code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="left">Group</th>
<th align="right">M1Left</th>
<th align="right">M2Left</th>
<th align="right">M3Left</th>
<th align="right">Foramen</th>
<th align="right">Pbone</th>
<th align="right">Length</th>
<th align="right">Height</th>
<th align="right">Rostrum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90</td>
<td align="left">multiplex</td>
<td align="right">1841</td>
<td align="right">1562</td>
<td align="right">1585</td>
<td align="right">3750</td>
<td align="right">5024</td>
<td align="right">2232</td>
<td align="right">821</td>
<td align="right">430</td>
</tr>
<tr class="even">
<td>91</td>
<td align="left">subterraneous</td>
<td align="right">1770</td>
<td align="right">1459</td>
<td align="right">1542</td>
<td align="right">3856</td>
<td align="right">4542</td>
<td align="right">2140</td>
<td align="right">755</td>
<td align="right">405</td>
</tr>
<tr class="odd">
<td>92</td>
<td align="left">subterraneous</td>
<td align="right">1785</td>
<td align="right">1573</td>
<td align="right">1616</td>
<td align="right">4165</td>
<td align="right">3928</td>
<td align="right">2295</td>
<td align="right">767</td>
<td align="right">425</td>
</tr>
<tr class="even">
<td>93</td>
<td align="left">multiplex</td>
<td align="right">2095</td>
<td align="right">1660</td>
<td align="right">1870</td>
<td align="right">3937</td>
<td align="right">5218</td>
<td align="right">2355</td>
<td align="right">842</td>
<td align="right">490</td>
</tr>
<tr class="odd">
<td>94</td>
<td align="left">multiplex</td>
<td align="right">1976</td>
<td align="right">1666</td>
<td align="right">1704</td>
<td align="right">4058</td>
<td align="right">5235</td>
<td align="right">2335</td>
<td align="right">814</td>
<td align="right">481</td>
</tr>
<tr class="even">
<td>95</td>
<td align="left">multiplex</td>
<td align="right">1980</td>
<td align="right">1643</td>
<td align="right">1950</td>
<td align="right">3569</td>
<td align="right">6020</td>
<td align="right">2355</td>
<td align="right">815</td>
<td align="right">460</td>
</tr>
</tbody>
</table>
<pre class="r"><code>cat(&quot;Count of predicted class:&quot;)</code></pre>
<pre><code>## Count of predicted class:</code></pre>
<pre class="r"><code>table(uk$Group)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">multiplex</th>
<th align="right">subterraneous</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">128</td>
<td align="right">71</td>
</tr>
</tbody>
</table>
<pre class="r"><code># ## decouple the predictions 
# uk_multi=subset(uk, Group==&quot;multiplex&quot;)
# uk_subten=subset(uk, Group==&quot;subterraneous&quot;)
# 
# nrow(uk_multi) ## number of samples predicted as multiplex
# nrow(uk_subten) ## number of samples predicted as subterraneous
# 
# rownames(uk_multi) ## sample numbers of the multiplex classified 
# rownames(uk_subten) ## sample numbers of the subterraneous classified 
############################################################################</code></pre>

    </div>

    


    

<div class="article-tags">
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/r/">R</a>
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/statistics/">Statistics</a>
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/modern-applied-statistics-i/">Modern Applied Statistics I</a>
  
</div>



    
      








  
  
    
  
  





  
  
  
  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/achalneupane.github.io/authors/achal-neupane/"></a></h5>
      
      
      <ul class="network-icon" aria-hidden="true">
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/achalneupane.github.io/post/longitudinal_data_analysis_and_mixed_models_ii/">Longitudinal Data Analysis and Mixed Models II</a></li>
          
          <li><a href="/achalneupane.github.io/post/longitudinal_data_analysis_and_mixed_models_i/">Longitudinal Data Analysis and Mixed Models I</a></li>
          
          <li><a href="/achalneupane.github.io/post/quantile_regression/">Quantile Regression</a></li>
          
          <li><a href="/achalneupane.github.io/post/survival_analysis/">Survival Analysis</a></li>
          
          <li><a href="/achalneupane.github.io/post/generalized_additive_models_and_spline_models/">Generalized Additive Models and Spline Models</a></li>
          
        </ul>
      </div>
      
    

    

    


  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
    

    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/achalneupane.github.io/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/achalneupane.github.io/js/academic.min.16bbb3750feb7244c9bc409a5a4fe678.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/achalneupane.github.io/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/achalneupane.github.io/terms/">Terms</a>
        
  </p>
  

  <p class="powered-by">
    © 2019 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
