<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.4.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Achal Neupane">

  
  
  
    
  
  <meta name="description" content="Statistics series">

  
  <link rel="alternate" hreflang="en-us" href="/achalneupane.github.io/post/logistic_regression_glm_ii/">

  


  

  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/achalneupane.github.io/css/academic.min.3072054fc61fe865aa34bcb366de141d.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-145752794-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/achalneupane.github.io/index.webmanifest">
  <link rel="icon" type="image/png" href="/achalneupane.github.io/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/achalneupane.github.io/img/icon-192.png">

  <link rel="canonical" href="/achalneupane.github.io/post/logistic_regression_glm_ii/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@achalneupane">
  <meta property="twitter:creator" content="@achalneupane">
  
  <meta property="og:site_name" content="Achal Neupane">
  <meta property="og:url" content="/achalneupane.github.io/post/logistic_regression_glm_ii/">
  <meta property="og:title" content="Logistic Regression&amp;GLM-II | Achal Neupane">
  <meta property="og:description" content="Statistics series"><meta property="og:image" content="/achalneupane.github.io/img/icon-192.png">
  <meta property="twitter:image" content="/achalneupane.github.io/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2019-08-15T17:26:23-05:00">
    
    <meta property="article:modified_time" content="2019-08-15T17:26:23-05:00">
  

  


  





  <title>Logistic Regression&amp;GLM-II | Achal Neupane</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/achalneupane.github.io/">Achal Neupane</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#impact"><span>Impact</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#contact"><span>Contact</span></a>
        </li>

        
        

      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article" itemscope itemtype="http://schema.org/Article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1 itemprop="name">Logistic Regression&amp;GLM-II</h1>

  

  
    



<meta content="2019-08-15 17:26:23 -0500 CDT" itemprop="datePublished">
<meta content="2019-08-15 17:26:23 -0500 CDT" itemprop="dateModified">

<div class="article-metadata">

  
  
  
  
  <div>
    



  <span itemprop="author name" itemtype="http://schema.org/Person"><a href="/achalneupane.github.io/authors/achal-neupane/"><strong>Achal Neupane</strong></a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
    
    <time>Aug 15, 2019</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    18 min read
  </span>
  

  
  
  

  
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/achalneupane.github.io/post/logistic_regression_glm_ii/&amp;text=Logistic%20Regression&amp;amp;GLM-II" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/achalneupane.github.io/post/logistic_regression_glm_ii/&amp;t=Logistic%20Regression&amp;amp;GLM-II" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Logistic%20Regression&amp;amp;GLM-II&amp;body=/achalneupane.github.io/post/logistic_regression_glm_ii/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/achalneupane.github.io/post/logistic_regression_glm_ii/&amp;title=Logistic%20Regression&amp;amp;GLM-II" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Logistic%20Regression&amp;amp;GLM-II%20/achalneupane.github.io/post/logistic_regression_glm_ii/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/achalneupane.github.io/post/logistic_regression_glm_ii/&amp;title=Logistic%20Regression&amp;amp;GLM-II" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<p>Answer all questions specified on the problem and include a discussion on how your results answered/addressed the question.</p>
<p>Submit your  file with the knitted  (or knitted Word Document saved as a PDF). If you are having trouble with .rmd, let us know and we will help you, but both the .rmd and the PDF are required.</p>
<p>This file can be used as a skeleton document for your code/write up. Please follow the instructions found under Content for Formatting and Guidelines. No code should be in your PDF write-up unless stated otherwise.</p>
<p>For any question asking for plots/graphs, please do as the question asks as well as do the same but using the respective commands in the GGPLOT2 library. (So if the question asks for one plot, your results should have two plots. One produced using the given R-function and one produced from the GGPLOT2 equivalent). This doesn’t apply to questions that don’t specifically ask for a plot, however I still would encourage you to produce both.</p>
<p>You do not need to include the above statements.</p>
<p>Please do the following problems from the text book R Handbook and stated.</p>
<ol style="list-style-type: decimal">
<li><p>Use the  data from the  library to answer the following questions</p>
<ol style="list-style-type: lower-alpha">
<li><p>Construct graphical and numerical summaries that will show the relationship between tumor size and the number of recurrent tumors. Discuss your discovery. (Hint: mosaic plot may be a great way to assess this)</p></li>
<li><p>Build a Poisson regression that estimates the effect of size of tumor on the number of recurrent tumors. Discuss your results.</p></li>
</ol></li>
</ol>
<pre class="r"><code>data(&quot;bladdercancer&quot;, package = &quot;HSAUR3&quot;)
# base R plot version
# head(bladdercancer)
cat(&quot;#1a&quot;)</code></pre>
<pre><code>## #1a</code></pre>
<pre class="r"><code>mosaicplot(xtabs( ~ number + tumorsize, data = bladdercancer),
           main = &quot;base R: The Number of recurrent tumors compared with tumor size&quot;,
           shade = TRUE)

# ggplot version:
# install.packages(&#39;ggmosaic&#39;)
library(ggmosaic)</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data = bladdercancer) +
  geom_mosaic(aes(x = product(tumorsize, number), fill = tumorsize), na.rm =
                FALSE) +
  labs(x = &quot;Number&quot;, x = &quot;Tumour Size&quot;, title = &#39;ggplot: The Number of recurrent tumors compared with tumor size&#39;)</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<pre class="r"><code># We can also visualize this by creating percentage table using `prop.table`
# function.
table_rows_percentage &lt;-
  table(bladdercancer$tumorsize, bladdercancer$number)
colnames(table_rows_percentage) &lt;-
  c(&quot;Tumour_1 (counts)&quot;,
    &quot;Tumour_2 (counts)&quot;,
    &quot;Tumour_3 (counts)&quot;,
    &quot;Tumour_4 (counts)&quot;)
cat(&quot;Table of tumour number and frequency:&quot;)</code></pre>
<pre><code>## Table of tumour number and frequency:</code></pre>
<pre class="r"><code>table_rows_percentage</code></pre>
<pre><code>##        
##         Tumour_1 (counts) Tumour_2 (counts) Tumour_3 (counts)
##   &lt;=3cm                15                 5                 1
##   &gt;3cm                  5                 2                 1
##        
##         Tumour_4 (counts)
##   &lt;=3cm                 1
##   &gt;3cm                  1</code></pre>
<pre class="r"><code># bladdercancer %&gt;%
#   group_by(tumorsize,number) %&gt;%
#   summarize(freq = n()) %&gt;%
#   spread(number,freq,sep=&#39;_of_tumors_&#39;)
tt &lt;- prop.table(table_rows_percentage, 1)
colnames(tt) &lt;-
  c(&quot;Tumour_1(%)&quot;, &quot;Tumour_2(%)&quot;, &quot;Tumour_3(%)&quot;, &quot;Tumour_4(%)&quot;)
cat(&quot;Table of tumour number and frequency in %:&quot;)</code></pre>
<pre><code>## Table of tumour number and frequency in %:</code></pre>
<pre class="r"><code>tt</code></pre>
<pre><code>##        
##         Tumour_1(%) Tumour_2(%) Tumour_3(%) Tumour_4(%)
##   &lt;=3cm  0.68181818  0.22727273  0.04545455  0.04545455
##   &gt;3cm   0.55555556  0.22222222  0.11111111  0.11111111</code></pre>
<p>1a. <strong>Discussion:</strong></p>
<p>Based on the mosaic plot, frequency table or the percentage table above, we can tell that the observed frequency for 1 or 2 tumors greater than 3cm (&gt;3cm) is lower than expected and the observed frequency for 3 or 4 tumors less than or equal to 3 cm (&lt;=3cm) is also lower than what we would expect for this data.</p>
<p>1b.</p>
<p>Building a Poisson regression that estimates the effect of size of tumor on
the number of recurrent tumors.</p>
<pre class="r"><code>mod1 &lt;- glm(number ~ tumorsize,data=bladdercancer,family=poisson())
summary(mod1)</code></pre>
<pre><code>## 
## Call:
## glm(formula = number ~ tumorsize, family = poisson(), data = bladdercancer)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.6363  -0.3996  -0.3996   0.4277   1.7326  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)     0.3747     0.1768   2.120    0.034 *
## tumorsize&gt;3cm   0.2007     0.3062   0.655    0.512  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 12.80  on 30  degrees of freedom
## Residual deviance: 12.38  on 29  degrees of freedom
## AIC: 87.191
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>1b. <strong>Discussion</strong>:</p>
<p>model1 (mod1): If we test the model dropping the time variable. It shows that the intercept is significant (P&lt;0.05), but the tumour size is not significant.</p>
<p>Additionally, we can also test models considering the time interaction</p>
<pre class="r"><code>mod2 &lt;- glm(number ~time + tumorsize + tumorsize*time,data=bladdercancer,family=poisson(link=log))
summary(mod2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = number ~ time + tumorsize + tumorsize * time, family = poisson(link = log), 
##     data = bladdercancer)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.6943  -0.5581  -0.2413   0.2932   1.4644  
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)         0.03957    0.43088   0.092    0.927
## time                0.02138    0.02418   0.884    0.377
## tumorsize&gt;3cm       0.46717    0.66713   0.700    0.484
## time:tumorsize&gt;3cm -0.01676    0.03821  -0.439    0.661
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 12.800  on 30  degrees of freedom
## Residual deviance: 11.566  on 27  degrees of freedom
## AIC: 90.377
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>1b. <strong>Discussion:</strong></p>
<p>model2 (mod2): If we consider time interaction with the tumour size, we can clearly see that none of the variables are significant.</p>
<p>If we remove time interaction from above model, we get</p>
<pre class="r"><code>mod3 &lt;- glm(number ~ time + tumorsize,data=bladdercancer,family=poisson())
summary(mod3)</code></pre>
<pre><code>## 
## Call:
## glm(formula = number ~ time + tumorsize, family = poisson(), 
##     data = bladdercancer)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.8183  -0.4753  -0.2923   0.3319   1.5446  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)    0.14568    0.34766   0.419    0.675
## time           0.01478    0.01883   0.785    0.433
## tumorsize&gt;3cm  0.20511    0.30620   0.670    0.503
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 12.800  on 30  degrees of freedom
## Residual deviance: 11.757  on 28  degrees of freedom
## AIC: 88.568
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>1b. <strong>Discussions:</strong></p>
<p>model3 (mod3): If we drop time interaction from previous model (mod2), we still do not get anything significant with the time or tumour size. However, the AIC value drops to 88.56.</p>
<p>In all three models we compared, we can also see that the residual and null deviance values are low compared to the degrees of freedom. If our Null Deviance is really small, it means that the Null Model explains the data pretty well. Likewise with your Residual Deviance.</p>
<p>Additionaly, we can perform a Chi-squared test for the Null deviance to check
whether any of the predictors have an influence on the response variables in
our three models using function <code>pchisq</code>:</p>
<pre class="r"><code># Source: https://stat.ethz.ch/education/semesters/as2015/asr/Uebungen/Uebungen/solution8.pdf
pchisq((mod1$null.deviance-mod1$deviance), df = (mod1$df.null-mod1$df.residual), lower = FALSE)</code></pre>
<pre><code>## [1] 0.5171827</code></pre>
<pre class="r"><code>pchisq((mod2$null.deviance-mod2$deviance), df = (mod2$df.null-mod2$df.residual), lower = FALSE)</code></pre>
<pre><code>## [1] 0.7448414</code></pre>
<pre class="r"><code>pchisq((mod3$null.deviance-mod3$deviance), df  = (mod3$df.null-mod3$df.residual), lower = FALSE)</code></pre>
<pre><code>## [1] 0.5935891</code></pre>
<p>The p-values in all three models are larger than 0.05, which tells us that there is no significant predictor in our model.</p>
<p>Additionally, if we can compare all three models we built above for analysis of deviance using ANOVA:</p>
<pre class="r"><code>anova(mod1,mod2,mod3,test=&#39;Chisq&#39;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: number ~ tumorsize
## Model 2: number ~ time + tumorsize + tumorsize * time
## Model 3: number ~ time + tumorsize
##   Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
## 1        29     12.380                     
## 2        27     11.566  2  0.81458   0.6655
## 3        28     11.757 -1 -0.19095   0.6621</code></pre>
<p>1b. <strong>Discussion</strong></p>
<p>Here as well, we do not find any of these models to be significant.</p>
<p>Final conclusion: Based on these analysis we can tell that the acceptance of the null hypothesis is evident in this case because there is nothing within the data to explain an increment in the number of tumors. Since we tested both tumour size and time variables, we can tell that <strong>neither time</strong> nor the <strong>tumour size</strong> have any effect on increasing <strong>number</strong> of tumours.</p>
<ol start="2" style="list-style-type: decimal">
<li>The following data is the number of new AIDS cases in Belgium between the years 1981-1993. Let <span class="math inline">\(t\)</span> denote time
<p>Do the following</p>
<ol style="list-style-type: lower-alpha">
<li><p>Plot the relationship between AIDS cases against time. Comment on the plot</p></li>
<li><p>Fit a Poisson regression model <span class="math inline">\(log(\mu_i)=\beta_0+\beta_1t_i\)</span>. Comment on the model parameters and residuals (deviance) vs Fitted plot.</p></li>
<li><p>Now add a quadratic term in time ( ) and fit the model. Comment on the model parameters and assess the residual plots.</p></li>
<li><p>Compare the two models using AIC. Which model is better?</p></li>
<li><p>Use -function to perform <span class="math inline">\(\chi^2\)</span> test for model selection. Did adding the quadratic term improve model?</p></li>
</ol></li>
</ol>
<pre class="r"><code>y = c(12, 14, 33, 50, 67, 74, 123, 141, 165, 204, 253, 246, 240)
t = 1:13

data &lt;- as.data.frame(cbind(t, y))

cat(&quot;#2a (base R plot version)&quot;)</code></pre>
<pre><code>## #2a (base R plot version)</code></pre>
<pre class="r"><code>plot(y ~ t,
     main = &quot;base R: Number of AIDs cases from 1981-1993&quot;,
     xlab = &quot;Time in Years from 1981&quot;,
     ylab = &quot;Number of Aids cases&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>cat(&quot;#2a ggplot version&quot;)</code></pre>
<pre><code>## #2a ggplot version</code></pre>
<pre class="r"><code>ggplot() + aes(x = t, y = y) + geom_point() + labs(title = &quot;ggplot: Number of AIDs cases from 1981-1993&quot;, x = &quot;Time in Years from 1981&quot;, y = &quot;Number of Aids cases&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code>cat(&quot;#2b&quot;)</code></pre>
<pre><code>## #2b</code></pre>
<pre class="r"><code>#Poisson model
aids.pois &lt;- glm(y ~ t, data = data, family = &quot;poisson&quot;)
summary(aids.pois)</code></pre>
<pre><code>## 
## Call:
## glm(formula = y ~ t, family = &quot;poisson&quot;, data = data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -4.6784  -1.5013  -0.2636   2.1760   2.7306  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) 3.140590   0.078247   40.14   &lt;2e-16 ***
## t           0.202121   0.007771   26.01   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 872.206  on 12  degrees of freedom
## Residual deviance:  80.686  on 11  degrees of freedom
## AIC: 166.37
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code># Coefficients
exp(coef(aids.pois)) # coefficients</code></pre>
<pre><code>## (Intercept)           t 
##   23.117491    1.223996</code></pre>
<pre class="r"><code>exp(confint(aids.pois)) # confidence interval</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 19.789547 26.894433
## t            1.205624  1.242922</code></pre>
<pre class="r"><code>#use code below for residual plots
plot(aids.pois, which = 1, main = &quot;base R: Residual Vs fitted plot for y ~ t&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-7-3.png" width="672" /></p>
<pre class="r"><code># ggplot version
# https://stackoverflow.com/questions/36731027/how-can-i-plot-the-residuals-of-lm-with-ggplot

# cc &lt;- data.frame(aids.pois$residuals, aids.pois$fitted.values)
#
# ggplot(cc, aes(x = aids.pois.fitted.values, y = aids.pois.residuals)) +
#   geom_point() +
#   geom_abline()

# ggplot(cc, aes(x = aids.pois.fitted.values, y = aids.pois.residuals)) +
#   geom_smooth(method=&quot;loess&quot;, color=&quot;red&quot;, se=FALSE) +
#   geom_hline(yintercept = 0, linetype=2, color=&quot;darkgrey&quot;) +
#   geom_point()+ labs(title = &quot;ggplot: Residual Vs fitted plot&quot;)

# ggplot version
ggplot(aids.pois, aes(x = .fitted, y = .resid)) + geom_point() + geom_smooth(group = 1, formula = y ~ x) + labs(title = &quot;ggplot: Residual Vs fitted plot for y ~ t&quot;)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-7-4.png" width="672" /></p>
<pre class="r"><code>cat(&quot;#2c&quot;)</code></pre>
<pre><code>## #2c</code></pre>
<pre class="r"><code>data$t2 &lt;- data$t ^ 2
aids2.pois &lt;- glm(y ~ t + t2, data = data, family = &quot;poisson&quot;)
summary(aids2.pois)</code></pre>
<pre><code>## 
## Call:
## glm(formula = y ~ t + t2, family = &quot;poisson&quot;, data = data)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -1.45903  -0.64491   0.08927   0.67117   1.54596  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  1.901459   0.186877  10.175  &lt; 2e-16 ***
## t            0.556003   0.045780  12.145  &lt; 2e-16 ***
## t2          -0.021346   0.002659  -8.029 9.82e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 872.2058  on 12  degrees of freedom
## Residual deviance:   9.2402  on 10  degrees of freedom
## AIC: 96.924
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code># Coefficients
exp(coef(aids2.pois)) # coefficients</code></pre>
<pre><code>## (Intercept)           t          t2 
##   6.6956535   1.7436895   0.9788799</code></pre>
<pre class="r"><code>exp(confint(aids2.pois)) # confidence interval</code></pre>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) 4.5976982 9.5678396
## t           1.5965138 1.9104525
## t2          0.9737254 0.9839292</code></pre>
<pre class="r"><code>#use code below for residual plots
plot(aids2.pois, which = 1, main = &quot;base R: Residual Vs fitted plot for y ~ t + t2&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-7-5.png" width="672" /></p>
<pre class="r"><code># ggplot version
ggplot(aids2.pois, aes(x = .fitted, y = .resid)) + geom_point() + labs(title = &quot;ggplot: Residuals Vs fitted plot for y ~ t + t2&quot;) + geom_smooth()</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/achalneupane.github.io/post/Logistic_Regression_GLM_II_files/figure-html/unnamed-chunk-7-6.png" width="672" /></p>
<pre class="r"><code>cat(&quot;#2d&quot;)</code></pre>
<pre><code>## #2d</code></pre>
<pre class="r"><code>AIC(aids.pois)</code></pre>
<pre><code>## [1] 166.3698</code></pre>
<pre class="r"><code>AIC(aids2.pois)</code></pre>
<pre><code>## [1] 96.92358</code></pre>
<pre class="r"><code>cat(&quot;#2e&quot;)</code></pre>
<pre><code>## #2e</code></pre>
<pre class="r"><code>anova(aids.pois, aids2.pois, test = &quot;Chisq&quot;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: y ~ t
## Model 2: y ~ t + t2
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1        11     80.686                          
## 2        10      9.240  1   71.446 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Discussions:</strong></p>
<p>2a. The number of new AIDS cases has an increasing trend over time and seems to be leveling off between 1981-1991 then it remains somewhat unchanged until 1993. The maximum number of new AIDS cases occurs in 1991.</p>
<p>2b. Both (b0) and (b1) are statistically significant from zero.</p>
<p>Interpretation of the coefficients calculated by exponentiating the estimates:</p>
<p>exp(b1) =1.22 : A one year increase will result in a 22% increase in the mean number of new AIDs cases.</p>
<p>exp(b0) =23.1 : When t=0, the average number of AID cases is 23.1.</p>
<p>Likewise, comparing the residual deviance of the model, we can tell that the model is over-spread by 7.80 times on 11 degrees of freedom. Based on the residual plot, we can tell that at time 1, 2, and 13 the residual values are further away from zero indicating they are outliers. Additionally, there is a clear pattern to the residual plot which indicates that mean does not increase as the variance increase because there is not a constant spread in the residuals.</p>
<p>Additionally, we can see a curved pattern in the Residual vs. Fitted plot. This could tell us that a transformation or adding a quadratic term to the model would be suitable.</p>
<p>2c. All the model parameters are statistically significant from zero.<br />
Interpretation of the coefficients calculated by exponentiating the estimates:</p>
<p>exp(b1) =1.74: Taking all other parameters constant, a one year increase will result in a 74% increase in the mean number of new AID cases.</p>
<p>exp(b2) =0.98 : Taking all other parameters constant, a one year increase will result in a 2% decrease in the mean number of new AID cases.</p>
<p>exp(b0) =6.7 : When t=0 and t^2=0, the average number of AID cases is 6.7.</p>
<p>Additionally, the residuals vs. fitted values plot looks much better than model one. The residuals seems randomly distributed around 0.</p>
<p>2d. Based on the AIC values and the residual plots, model 2 is a better fit for this data.</p>
<p>2e.Based on the chi-square test statistic and p-value—in this case we reject the null hypothesis at the  = 0.05 level that model 1 is true. We can tell that the larger model is better, which in this case, adding the quadratic term did improve the model.</p>
<ol start="3" style="list-style-type: decimal">
<li>Load the  dataset from  library. The dataset contains information on ten thousand customers. The aim here is to predict which customers will default on their credit card debt. It is a 4 dimensional dataset with 10000 observations. You had developed a logistic regression model on HW #2. Now consider the following two models
<p>For the two competing models do the following</p>
<ol style="list-style-type: lower-alpha">
<li><p>With the whole data compare the two models (Use AIC and/or error rate)</p></li>
<li><p>Use validation set approach and choose the best model. Be aware that we have few people who defaulted in the data.</p></li>
<li><p>Use LOOCV approach and choose the best model</p></li>
<li><p>Use 10-fold cross-validation approach and choose the best model</p></li>
</ol>
<p>Report validation misclassification (error) rate for both models in each of the three assessment methods. Discuss your results.</p></li>
</ol>
<pre class="r"><code>data(&quot;Default&quot;, package = &quot;ISLR&quot;)
Default$default&lt;-as.numeric(Default$default==&quot;Yes&quot;)

mod.log1&lt;-glm(default ~ student + balance , data = Default, family = binomial())
# summary(mod.log1)


cat (&quot;#3a&quot;)</code></pre>
<pre><code>## #3a</code></pre>
<pre class="r"><code>mod.log2&lt;-glm(default ~ balance , data = Default, family = binomial())
cat(&quot;AIC for mod.log1:&quot;)</code></pre>
<pre><code>## AIC for mod.log1:</code></pre>
<pre class="r"><code># cat(&quot;AIC(mod.log1) =&quot;, AIC(mod.log1))
AIC(mod.log1)</code></pre>
<pre><code>## [1] 1577.682</code></pre>
<pre class="r"><code>cat(&quot;AIC for mod.log2:&quot;)</code></pre>
<pre><code>## AIC for mod.log2:</code></pre>
<pre class="r"><code>AIC(mod.log2)</code></pre>
<pre><code>## [1] 1600.452</code></pre>
<pre class="r"><code># cat(&quot;AIC(mod.log2) =&quot;, AIC(mod.log2))
anova(mod.log1, mod.log2, test=&quot;Chisq&quot;)</code></pre>
<pre><code>## Analysis of Deviance Table
## 
## Model 1: default ~ student + balance
## Model 2: default ~ balance
##   Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
## 1      9997     1571.7                          
## 2      9998     1596.5 -1   -24.77 6.459e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>cat(&quot;#3b Validation approach&quot;)</code></pre>
<pre><code>## #3b Validation approach</code></pre>
<pre class="r"><code>index&lt;-sample(1:nrow(Default), size=0.6*nrow(Default))
train&lt;- Default[index, ]
val&lt;- Default[-index, ]


mod.train1&lt;-glm(default ~ student + balance , data = train, family = binomial())
# summary(mod.train1)
mod.train2&lt;-glm(default ~ balance , data = train, family = binomial())
# summary(mod.train2)
pred1&lt;-predict(mod.train1, val, type = &quot;response&quot;)
pred2&lt;-predict(mod.train2, val, type = &quot;response&quot;)

cat(&quot;Error rate: &quot;)</code></pre>
<pre><code>## Error rate:</code></pre>
<pre class="r"><code>err.rate1&lt;- mean((pred1&gt;0.5 &amp; val$default==0) | (pred1&lt;0.5 &amp; val$default==1))
err.rate2&lt;- mean((pred2&gt;0.5 &amp; val$default==0) | (pred2&lt;0.5 &amp; val$default==1))

cat(&quot;Error rate of model1 =&quot;, err.rate1)</code></pre>
<pre><code>## Error rate of model1 = 0.0265</code></pre>
<pre class="r"><code>cat(&quot;Error rate of model2 =&quot;, err.rate2)</code></pre>
<pre><code>## Error rate of model2 = 0.02725</code></pre>
<pre class="r"><code>cat(&quot;#3c LOOCV&quot;)</code></pre>
<pre><code>## #3c LOOCV</code></pre>
<pre class="r"><code>library(boot)

cost &lt;- function(r, pi = 0) mean(abs(r-pi) &gt; 0.5)
cv.err &lt;- cv.glm(Default,mod.log1, cost)$delta
cv.err2 &lt;- cv.glm(Default, mod.log2, cost)$delta
cat(&quot;LOOCV of model1&quot;)</code></pre>
<pre><code>## LOOCV of model1</code></pre>
<pre class="r"><code>cv.err</code></pre>
<pre><code>## [1] 0.0267 0.0267</code></pre>
<pre class="r"><code>cat(&quot;LOOCV of model2&quot;)</code></pre>
<pre><code>## LOOCV of model2</code></pre>
<pre class="r"><code>cv.err2</code></pre>
<pre><code>## [1] 0.02750000 0.02749994</code></pre>
<pre class="r"><code>cat(&quot;#3d 10-fold cross validation&quot;)</code></pre>
<pre><code>## #3d 10-fold cross validation</code></pre>
<pre class="r"><code>cv.err1.10 &lt;- cv.glm(Default, mod.log1, cost ,K=10)$delta
cv.err2.10 &lt;- cv.glm(Default, mod.log2, cost ,K=10)$delta

cat(&quot;10-fold cross validation of Model1&quot;)</code></pre>
<pre><code>## 10-fold cross validation of Model1</code></pre>
<pre class="r"><code>cv.err1.10</code></pre>
<pre><code>## [1] 0.02660 0.02661</code></pre>
<pre class="r"><code>cat(&quot;10-fold cross validation of Model2&quot;)</code></pre>
<pre><code>## 10-fold cross validation of Model2</code></pre>
<pre class="r"><code>cv.err2.10</code></pre>
<pre><code>## [1] 0.02760 0.02757</code></pre>
<p><strong>Discussions:</strong></p>
<p>3a. The first model with both student and balance has the smaller AIC. The anova-function was also used to perform a chi-square test for model selection and again concluded the first model was better.</p>
<p>3b. Splitted the data into 60/40 between the training and validation data sets and made sure the default rate was similar between the two dataset, then fitted the models to the training data and then used the validation set to calculate the error rate using 0.5 as out threshold.</p>
<p>For model 1, the MSE is 0.023.</p>
<p>For model 2, the MSE is 0.024.</p>
<p>Based on these values we would chose model 1 as our best model. We will also examine other validation techniques below.</p>
<p>3c. LOOCV prediction error is adjusted for bias and we still want the smallest prediction errors.
For model 1, the adjusted prediction error is 0.0267.</p>
<p>For model 2, the adjusted prediction error is 0.02749994.</p>
<p>Therefore, we choose model 1 as the best model because it has the smaller adjusted prediction rate using the LOOCV approach.</p>
<p>3d. Using K=10 for the 10-fold cross-validation approach, we obtain the following error rates:</p>
<p>For model 1, the CV error rate is 0.02667
For model 2, the CV error rate is 0.0278</p>
<p>Again, we can choose model 1 as our best model. Though it was little easier to calculate the 10-fold cross validation error rate than the LOOCV error rate but our conclusion is the same.</p>
<ol start="4" style="list-style-type: decimal">
<li>In the  library load the  dataset. This contains Daily percentage returns for the S&amp;P 500 stock index between 2001 and 2005. There are 1250 observations and 9 variables. The variable of interest is Direction which is a factor with levels Down and Up indicating whether the market had a positive or negative return on a given day. Since the goal is to predict the direction of the stock market in the future, here it would make sense to use the data from years 2001 - 2004 as training and 2005 as validation. According to this, create a training set and testing set. Perform logistic regression and assess the error rate.</li>
</ol>
<pre class="r"><code>data(&quot;Smarket&quot;, package = &quot;ISLR&quot;)
Smarket$Direction &lt;- as.numeric(Smarket$Direction == &quot;Up&quot;)

train.mark &lt;- subset(Smarket, Year &lt;= 2004)
val.mark &lt;- subset(Smarket, Year &gt; 2004)


#Model 1
mod.train.mark &lt;-
  glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 ,
      data = train.mark,
      family = binomial())
summary(mod.train.mark)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5, family = binomial(), 
##     data = train.mark)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.339  -1.189   1.070   1.163   1.326  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  0.032269   0.063379   0.509    0.611
## Lag1        -0.055510   0.051706  -1.074    0.283
## Lag2        -0.044218   0.051681  -0.856    0.392
## Lag3         0.008918   0.051517   0.173    0.863
## Lag4         0.008556   0.051514   0.166    0.868
## Lag5        -0.003243   0.051089  -0.063    0.949
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1383.3  on 997  degrees of freedom
## Residual deviance: 1381.3  on 992  degrees of freedom
## AIC: 1393.3
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<pre class="r"><code>err.rate1 &lt;-
  mean((
    predict(mod.train.mark, val.mark, type = &quot;response&quot;) - val.mark$Direction
  ) ^ 2)
cat(&quot;Error rate model1:&quot;)</code></pre>
<pre><code>## Error rate model1:</code></pre>
<pre class="r"><code>err.rate1</code></pre>
<pre><code>## [1] 0.2483559</code></pre>
<pre class="r"><code>#Model 2
mod.train.mark2 &lt;-
  glm(Direction ~ Lag1 + Lag2 + Lag3,
      data = train.mark,
      family = binomial())
summary(mod.train.mark2)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Direction ~ Lag1 + Lag2 + Lag3, family = binomial(), 
##     data = train.mark)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.338  -1.189   1.072   1.163   1.335  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  0.032230   0.063377   0.509    0.611
## Lag1        -0.055523   0.051709  -1.074    0.283
## Lag2        -0.044300   0.051674  -0.857    0.391
## Lag3         0.008815   0.051495   0.171    0.864
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1383.3  on 997  degrees of freedom
## Residual deviance: 1381.4  on 994  degrees of freedom
## AIC: 1389.4
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<pre class="r"><code>err.rate2 &lt;-
  mean((
    predict(mod.train.mark2, val.mark, type = &quot;response&quot;) - val.mark$Direction
  ) ^ 2)
cat(&quot;Error rate model2:&quot;)</code></pre>
<pre><code>## Error rate model2:</code></pre>
<pre class="r"><code>err.rate2</code></pre>
<pre><code>## [1] 0.2483144</code></pre>
<p><strong>Discussions:</strong></p>
<p>The error rate for model 1 which includes predictor variables lag 1-5 is: 0.4126984.</p>
<p>The error rate for model 2 which includes predictor variables lag 1-3 is: 0.4087302.</p>
<p>We can choose the simpler model 2 based on the error rate. This error rate suggests that we are able to predict the direction of the stock market. We can predict the right outcome at around 60% of the time, which is still better than predicting randomly.</p>

    </div>

    


    

<div class="article-tags">
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/r/">R</a>
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/statistics/">Statistics</a>
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/modern-applied-statistics-i/">Modern Applied Statistics I</a>
  
</div>



    
      








  
  
    
  
  





  
  
  
  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/achalneupane.github.io/authors/achal-neupane/"></a></h5>
      
      
      <ul class="network-icon" aria-hidden="true">
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/achalneupane.github.io/post/density_estimation/">Density Estimation</a></li>
          
          <li><a href="/achalneupane.github.io/post/graphical_summary/">Graphical Summary</a></li>
          
          <li><a href="/achalneupane.github.io/post/logistic_regression_glm_i/">Logistic Regression&amp;GLM-I</a></li>
          
          <li><a href="/achalneupane.github.io/post/additional_graphs/">Additional graphs</a></li>
          
          <li><a href="/achalneupane.github.io/post/arrays/">Arrays</a></li>
          
        </ul>
      </div>
      
    

    

    


  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
    

    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/achalneupane.github.io/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/achalneupane.github.io/js/academic.min.16bbb3750feb7244c9bc409a5a4fe678.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/achalneupane.github.io/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/achalneupane.github.io/terms/">Terms</a>
        
  </p>
  

  <p class="powered-by">
    &copy; 2019 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
