<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.4.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Achal Neupane">

  
  
  
    
  
  <meta name="description" content="Statistics series">

  
  <link rel="alternate" hreflang="en-us" href="/achalneupane.github.io/post/additional_graphs/">

  


  

  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/achalneupane.github.io/css/academic.min.c66516cf97186fe7fa872ca1f0e4401a.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-145752794-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/achalneupane.github.io/index.webmanifest">
  <link rel="icon" type="image/png" href="/achalneupane.github.io/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/achalneupane.github.io/img/icon-192.png">

  <link rel="canonical" href="/achalneupane.github.io/post/additional_graphs/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@achalneupane">
  <meta property="twitter:creator" content="@achalneupane">
  
  <meta property="og:site_name" content="Achal Neupane">
  <meta property="og:url" content="/achalneupane.github.io/post/additional_graphs/">
  <meta property="og:title" content="Additional graphs | Achal Neupane">
  <meta property="og:description" content="Statistics series"><meta property="og:image" content="/achalneupane.github.io/img/icon-192.png">
  <meta property="twitter:image" content="/achalneupane.github.io/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2019-07-15T17:26:23-05:00">
    
    <meta property="article:modified_time" content="2019-07-15T17:26:23-05:00">
  

  


  





  <title>Additional graphs | Achal Neupane</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/achalneupane.github.io/">Achal Neupane</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#impact"><span>Impact</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#contact"><span>Contact</span></a>
        </li>

        
        

      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article" itemscope itemtype="http://schema.org/Article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1 itemprop="name">Additional graphs</h1>

  

  
    



<meta content="2019-07-15 17:26:23 -0500 CDT" itemprop="datePublished">
<meta content="2019-07-15 17:26:23 -0500 CDT" itemprop="dateModified">

<div class="article-metadata">

  
  
  
  
  <div>
    



  <span itemprop="author name" itemtype="http://schema.org/Person"><a href="/achalneupane.github.io/authors/achal-neupane/"><strong>Achal Neupane</strong></a></span>

  </div>
  
  

  
  <span class="article-date">
    
    
      
    
    <time>Jul 15, 2019</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    15 min read
  </span>
  

  
  
  

  
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/achalneupane.github.io/post/additional_graphs/&amp;text=Additional%20graphs" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/achalneupane.github.io/post/additional_graphs/&amp;t=Additional%20graphs" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Additional%20graphs&amp;body=/achalneupane.github.io/post/additional_graphs/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/achalneupane.github.io/post/additional_graphs/&amp;title=Additional%20graphs" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Additional%20graphs%20/achalneupane.github.io/post/additional_graphs/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/achalneupane.github.io/post/additional_graphs/&amp;title=Additional%20graphs" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<div id="general-instructions" class="section level1">
<h1>General Instructions</h1>
<p>There are 5 exercises, each is worth 10 points. You are required to solve at least one exercise in R, and at least one in SAS. You are required to provide five solutions, each solution will be worth 10 points.</p>
<p>For this exercise, you may use whatever graphics library you desire.</p>
<div id="experimental" class="section level4">
<h4>Experimental</h4>
<p>Again, you will be allowed to provide one solution using Python. Elaborate on the similarities and differences between Python function definitions and R or IML or Macro language.</p>
</div>
</div>
<div id="exercise-1." class="section level1">
<h1>Exercise 1.</h1>
<p>Load the <code>ncaa2018.csv</code> data set and create histograms, QQ-norm and box-whisker plots for <code>ELO</code>. Add a title to each plot, identifying the data.</p>
<pre class="r"><code>ncaa2018.dat = read.table(
  &quot;https://raw.githubusercontent.com/achalneupane/data/master/ncaa2018.csv&quot;,
  header = T,
  sep = &quot;,&quot;
)
# head(ncaa2018.dat)
# histogram
hist(ncaa2018.dat$ELO, xlab = &quot;ELO&quot;, main = &quot;Histogram of ELO&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code># QQ plot
qqnorm(ncaa2018.dat$ELO, main = &quot;Normal QQ plot&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<pre class="r"><code># box-whisker plot
boxplot(ncaa2018.dat$ELO, main = &quot;Box-whisker of ELO&quot;, ylab = &quot;ELO&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-1-3.png" width="672" /></p>
<div id="part-b" class="section level3">
<h3>Part b</h3>
<p>A common recommendation to address issues of non-normality is to transform data to correct for skewness. One common transformation is the log transform.</p>
<p>Transform <code>ELO</code> to <code>log(ELO)</code> and produce histograms, box-whisker and qqnorm plots of the transformed values. Are the transformed values more or less skewed than the original? (Note - the log transform is used to correct skewness, it is less useful for correcting kurtosis).</p>
<pre class="r"><code>hist(log(ncaa2018.dat$ELO), xlab = &quot;ELO&quot;, main = &quot;Histogram of log transformed ELO&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code># QQ plot
qqnorm(log(ncaa2018.dat$ELO), main = &quot;Normal QQ plot of log transformed ELO&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-2-2.png" width="672" /></p>
<pre class="r"><code># box-whisker plot
boxplot(log(ncaa2018.dat$ELO), main = &quot;Box-whisker of log transformed ELO&quot;, ylab = &quot;ELO&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-2-3.png" width="672" />
The values are less skewed now. Log transformation is a good way to display plot with skewedness in data.
# Exercise 2.</p>
<p>Review Exercise 4, Homework 6, where you calculated skewness and kurtosis. The reference for this exercise, <a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda35b.htm" class="uri">https://www.itl.nist.gov/div898/handbook/eda/section3/eda35b.htm</a>, gives four example statistical distributions. We will reproduce the histograms, and add qqnorm and box-whisker plots.</p>
</div>
<div id="part-a" class="section level2">
<h2>Part a</h2>
<p>Use the code below from lecture to draw 1000 samples from the normal distribution.</p>
<pre class="r"><code>norm.sample &lt;- rnorm(1000, mean=0, sd=1)</code></pre>
<p>Look up the corresponding <code>r*</code> functions in R for the Cauchy distribution (use location=0, scale=1), and the Weibull distribution (use shape = 1.5). For the double exponential, use you can use the <code>*laplace</code> functions from the <code>rmutil</code> library, or you can use <code>rexp(1000) - rexp(1000)</code></p>
<p>Draw 1000 samples from each of these distributions. Calculate skewness and kurtosis for each sample. You may use your own function, or use the <code>moments</code> library.</p>
<pre class="r"><code>dcauchy.1000 &lt;- rcauchy(1:1000, location = 0, scale = 1)
dweibull.1000 &lt;- rweibull(1:1000, shape = 1.5)
rexp.1000 &lt;- rexp(1000) - rexp(1000)



# Kurtosis
library(moments)

norm.sample.kurt &lt;- kurtosis(norm.sample, na.rm = TRUE)
norm.sample.kurt</code></pre>
<pre><code>## [1] 3.021838</code></pre>
<pre class="r"><code>dcauchy.1000.kurt &lt;- kurtosis(dcauchy.1000, na.rm = TRUE)
dcauchy.1000.kurt</code></pre>
<pre><code>## [1] 738.9989</code></pre>
<pre class="r"><code>dweibull.1000.kurt &lt;- kurtosis(dweibull.1000, na.rm = TRUE)
dweibull.1000.kurt</code></pre>
<pre><code>## [1] 4.200549</code></pre>
<pre class="r"><code>rexp.1000.kurt &lt;- kurtosis(rexp.1000, na.rm = TRUE)
rexp.1000.kurt</code></pre>
<pre><code>## [1] 4.822286</code></pre>
<pre class="r"><code>norm.sample.skew &lt;- skewness(norm.sample, na.rm = TRUE)
norm.sample.skew</code></pre>
<pre><code>## [1] -0.07906608</code></pre>
<pre class="r"><code>dcauchy.1000.skew &lt;- skewness(dcauchy.1000, na.rm = TRUE)
dcauchy.1000.skew</code></pre>
<pre><code>## [1] 25.7455</code></pre>
<pre class="r"><code>dweibull.1000.skew &lt;- skewness(dweibull.1000, na.rm = TRUE)
dweibull.1000.skew</code></pre>
<pre><code>## [1] 1.010605</code></pre>
<pre class="r"><code>rexp.1000.skew &lt;- skewness(rexp.1000, na.rm = TRUE)
rexp.1000.skew</code></pre>
<pre><code>## [1] 0.04160438</code></pre>
</div>
<div id="part-b-1" class="section level2">
<h2>Part b</h2>
<p>Plot the histograms for each distribution. Use <code>par(mfrow=c(2,2))</code> in your code chunk to combine the four histogram in a single plot. Add titles to the histograms indicating the distribution. Set the x-axis label to show the calculated skewness and kurtosis, i.e. <code>skewness = ####, kurtosis = ####</code></p>
<pre class="r"><code>par(mfrow=c(2,2))
hist(norm.sample, xlab = paste0(&quot;skewness = &quot;, norm.sample.skew , &quot;, kurtosis = &quot;, norm.sample.kurt), main = &quot;Histogram of Normal Distribution&quot;)
hist(dcauchy.1000, xlab = paste0(&quot;skewness = &quot;, dcauchy.1000.skew , &quot;, kurtosis = &quot;, dcauchy.1000.kurt), main = &quot;Histogram of Cauchy Distribution&quot;)
hist(dweibull.1000, xlab = paste0(&quot;skewness = &quot;, dweibull.1000.kurt , &quot;, kurtosis = &quot;, dweibull.1000.kurt), main = &quot;Histogram of Dweibull Distribution&quot;)
hist(rexp.1000, xlab = paste0(&quot;skewness = &quot;, rexp.1000.skew , &quot;, kurtosis = &quot;, rexp.1000.kurt), main = &quot;Histogram of double Exponential Distribution&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="part-c" class="section level2">
<h2>Part c</h2>
<p>Repeat Part b, but with QQ-norm plots.</p>
<pre class="r"><code>par(mfrow=c(2,2))
qqnorm(norm.sample, xlab = paste0(&quot;skewness = &quot;, norm.sample.skew , &quot;, kurtosis = &quot;, norm.sample.kurt), main = &quot;QQplot of Normal Distribution&quot;)
qqnorm(dcauchy.1000, xlab = paste0(&quot;skewness = &quot;, dcauchy.1000.skew , &quot;, kurtosis = &quot;, dcauchy.1000.kurt), main = &quot;QQplot of Cauchy Distribution&quot;)
qqnorm(dweibull.1000, xlab = paste0(&quot;skewness = &quot;, dweibull.1000.kurt , &quot;, kurtosis = &quot;, dweibull.1000.kurt), main = &quot;QQplot of Dweibull Distribution&quot;)
qqnorm(rexp.1000, xlab = paste0(&quot;skewness = &quot;, rexp.1000.skew , &quot;, kurtosis = &quot;, rexp.1000.kurt), main = &quot;QQplot of rexp Distribution&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="part-d" class="section level2">
<h2>Part d</h2>
<p>Repeat Part b, but with box-whisker plots.</p>
<pre class="r"><code>par(mfrow=c(2,2))
boxplot(norm.sample, xlab = paste0(&quot;skewness = &quot;, norm.sample.skew , &quot;, kurtosis = &quot;, norm.sample.kurt), main = &quot;Boxplot of Normal Distribution&quot;)
boxplot(dcauchy.1000, xlab = paste0(&quot;skewness = &quot;, dcauchy.1000.skew , &quot;, kurtosis = &quot;, dcauchy.1000.kurt), main = &quot;Boxplot of Cauchy Distribution&quot;)
boxplot(dweibull.1000, xlab = paste0(&quot;skewness = &quot;, dweibull.1000.kurt , &quot;, kurtosis = &quot;, dweibull.1000.kurt), main = &quot;Boxplot of Dweibull Distribution&quot;)
boxplot(rexp.1000, xlab = paste0(&quot;skewness = &quot;, rexp.1000.skew , &quot;, kurtosis = &quot;, rexp.1000.kurt), main = &quot;Boxplot of double rexp Distribution&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Hints for SAS. If you create the samples in IML, use</p>
<pre><code>Normal = j(1, 1000, .);
call randgen(Normal, &quot;NORMAL&quot;, 0, `);</code></pre>
<p>You can generate samples in the data step using</p>
<pre><code>do i = 1 to 1000;
  Normal = rand(&#39;NORMAL&#39;,0,1);
  output;
end;</code></pre>
<p>RAND doesn’t provide a Laplace option, but you can create samples from this distribution by</p>
<pre><code>rand(&#39;EXPONENTIAL&#39;)-rand(&#39;EXPONENTIAL&#39;);</code></pre>
<p>To group multiple plots, use</p>
<pre><code>ods graphics / width=8cm height=8cm;
ods layout gridded columns=2;
ods region;
 ... first plot

ods region;
 ... second plot

ods layout end;</code></pre>
<p>You might need to include</p>
<pre><code>ods graphics off;

ods graphics on;
ODS GRAPHICS / reset=All;</code></pre>
<p>to return the SAS graphics output to normal.</p>
</div>
<div id="exercise-3." class="section level2">
<h2>Exercise 3.</h2>
<p>We will create a series of graphs illustrating how the Poisson distribution approaches the normal distribution with large <span class="math inline">\(\lambda\)</span>. We will iterate over a sequence of <code>lambda</code>, from 2 to 64, doubling <code>lambda</code> each time. For each ‘lambda’ draw 1000 samples from the Poisson distribution.</p>
<p>Calculate the skewness of each set of samples, and produce histograms, QQ-norm and box-whisker plots. You can use <code>par(mfrow=c(1,3))</code> to display all three for one <code>lambda</code> in one line. Add <code>lambda=##</code> to the title of the histogram, and <code>skewness=##</code> to the title of the box-whisker plot.</p>
</div>
<div id="part-b." class="section level2">
<h2>Part b.</h2>
<p>Remember that <code>lambda</code> represents the mean of a discrete (counting) variable. At what size mean is Poisson data no longer skewed, relative to normally distributed data? You might run this 2 or 3 times, with different seeds; this number varies in my experience.</p>
<pre class="r"><code>library(moments)

rpois_skew_collect &lt;- {}
mu &lt;- 2

# set.seed(54321)
while(mu &lt;= 64){
  
rpois_values &lt;- rpois(1000, lambda = mu)
rpois_skew &lt;- skewness(rpois_values, na.rm = TRUE)
rpois_skew_collect[mu-1] &lt;- skewness(rpois_values)
# attaching all three plots together
par(mfrow=c(1,3))

# histogram
hist(rpois_values, main = paste0(&quot;Histogram of rpois Distribution for lambda = &quot;, mu))
# QQ plot
qqnorm(rpois_values, main = &quot;Normal QQ plot for poisson&quot;)

# box-whisker plot
boxplot(rpois_values, main = paste0(&quot;Box-whisker with skewness = &quot;, rpois_skew), ylab = &quot;rpois_values&quot;)
mu &lt;- mu*2
}</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-8-1.png" width="1152" /><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-8-2.png" width="1152" /><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-8-3.png" width="1152" /><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-8-4.png" width="1152" /><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-8-5.png" width="1152" /><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-8-6.png" width="1152" /></p>
<pre class="r"><code>plot(rpois_skew_collect)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-8-7.png" width="1152" /></p>
<p>It looks like the skewness starts to diminish significantly after mean size 32 (lambda) for poisson data.</p>
<p>If you do this in SAS, create a data table with data columns each representing a different <span class="math inline">\(\mu\)</span>. You can see combined histogram, box-whisker and QQ-norm, for all columns, by calling</p>
<pre><code>proc univariate data=Distributions plot;
run;</code></pre>
<p>At what <span class="math inline">\(\mu\)</span> is skewness of the Poisson distribution small enough to be considered normal?
It looks like after mu 60, skewness is small enough to be considered normal.</p>
</div>
</div>
<div id="exercise-4" class="section level1">
<h1>Exercise 4</h1>
<div id="part-a-1" class="section level2">
<h2>Part a</h2>
<p>Write a function that accepts a vector <code>vec</code>, a vector of integers, a main axis label and an x axis label. This function should
1. iterate over each element <span class="math inline">\(i\)</span> in the vector of integers
2. produce a histogram for <code>vec</code> setting the number of bins in the histogram to <span class="math inline">\(i\)</span>
3. label main and x-axis with the specified parameters.
4. label the y-axis to read <code>Frequency, bins =</code> and the number of bins.</p>
<p>Hint:
You can simplify this function by using the parameter <code>...</code> - see <code>?plot</code> or ?<code>hist</code></p>
<p>Writing the asked function</p>
<pre class="r"><code># vec &lt;- c(12,36,60)
# dat &lt;- hidalgo.dat[,1]
# i=1

plot.histograms &lt;- function(dat, vec, main, xlab){
  par(mfrow=c(1,length(vec)))
  for(i in 1:length(vec)){
  print(hist(dat, breaks = vec[i],  main = main, xlab = xlab, ylab = paste0(&#39;Frequency, bins = &#39;, vec[i])))

}
}

# now read the file
hidalgo.dat = read.table(&quot;https://raw.githubusercontent.com/achalneupane/data/master/hidalgo.dat&quot;,
                   header = T,
                   sep = &quot;,&quot;
)</code></pre>
</div>
<div id="part-b-2" class="section level2">
<h2>Part b</h2>
<p>Test your function with the <code>hidalgo</code> data set (see below), using bin numbers 12, 36, and 60. You should be able to call your function with something like</p>
<pre class="r"><code>plot.histograms(hidalgo.dat[,1],c(12,36,60), main=&quot;1872 Hidalgo issue&quot;,xlab= &quot;Thickness (mm)&quot;)</code></pre>
<pre><code>## $breaks
##  [1] 0.060 0.065 0.070 0.075 0.080 0.085 0.090 0.095 0.100 0.105 0.110 0.115
## [13] 0.120 0.125 0.130 0.135
## 
## $counts
##  [1]   3  35  93 131  45  24  19  35  31  32  15   8   7   5   1
## 
## $density
##  [1]  1.2396694 14.4628099 38.4297521 54.1322314 18.5950413  9.9173554
##  [7]  7.8512397 14.4628099 12.8099174 13.2231405  6.1983471  3.3057851
## [13]  2.8925620  2.0661157  0.4132231
## 
## $mids
##  [1] 0.0625 0.0675 0.0725 0.0775 0.0825 0.0875 0.0925 0.0975 0.1025 0.1075
## [11] 0.1125 0.1175 0.1225 0.1275 0.1325
## 
## $xname
## [1] &quot;dat&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<pre><code>## $breaks
##  [1] 0.064 0.066 0.068 0.070 0.072 0.074 0.076 0.078 0.080 0.082 0.084 0.086
## [13] 0.088 0.090 0.092 0.094 0.096 0.098 0.100 0.102 0.104 0.106 0.108 0.110
## [25] 0.112 0.114 0.116 0.118 0.120 0.122 0.124 0.126 0.128 0.130 0.132
## 
## $counts
##  [1]  4  1 33 52 21 38 34 79 33 10  4  3 19  8  9  5 12 20 17  9  9 10 18  9  3
## [26]  3  1  7  3  2  2  1  4  1
## 
## $density
##  [1]  4.132231  1.033058 34.090909 53.719008 21.694215 39.256198 35.123967
##  [8] 81.611570 34.090909 10.330579  4.132231  3.099174 19.628099  8.264463
## [15]  9.297521  5.165289 12.396694 20.661157 17.561983  9.297521  9.297521
## [22] 10.330579 18.595041  9.297521  3.099174  3.099174  1.033058  7.231405
## [29]  3.099174  2.066116  2.066116  1.033058  4.132231  1.033058
## 
## $mids
##  [1] 0.065 0.067 0.069 0.071 0.073 0.075 0.077 0.079 0.081 0.083 0.085 0.087
## [13] 0.089 0.091 0.093 0.095 0.097 0.099 0.101 0.103 0.105 0.107 0.109 0.111
## [25] 0.113 0.115 0.117 0.119 0.121 0.123 0.125 0.127 0.129 0.131
## 
## $xname
## [1] &quot;dat&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre><code>## $breaks
##  [1] 0.064 0.065 0.066 0.067 0.068 0.069 0.070 0.071 0.072 0.073 0.074 0.075
## [13] 0.076 0.077 0.078 0.079 0.080 0.081 0.082 0.083 0.084 0.085 0.086 0.087
## [25] 0.088 0.089 0.090 0.091 0.092 0.093 0.094 0.095 0.096 0.097 0.098 0.099
## [37] 0.100 0.101 0.102 0.103 0.104 0.105 0.106 0.107 0.108 0.109 0.110 0.111
## [49] 0.112 0.113 0.114 0.115 0.116 0.117 0.118 0.119 0.120 0.121 0.122 0.123
## [61] 0.124 0.125 0.126 0.127 0.128 0.129 0.130 0.131
## 
## $counts
##  [1]  3  1  0  1  7 26 20 32 11 10 20 18 11 23 42 37 15 18  7  3  2  2  1  2 10
## [26]  9  3  5  6  3  2  3  7  5  5 15  9  8  7  2  5  4  3  7  7 11  4  5  0  3
## [51]  3  0  1  0  4  3  1  2  2  0  2  0  0  1  3  1  1
## 
## $density
##  [1]  6.198347  2.066116  0.000000  2.066116 14.462810 53.719008 41.322314
##  [8] 66.115702 22.727273 20.661157 41.322314 37.190083 22.727273 47.520661
## [15] 86.776860 76.446281 30.991736 37.190083 14.462810  6.198347  4.132231
## [22]  4.132231  2.066116  4.132231 20.661157 18.595041  6.198347 10.330579
## [29] 12.396694  6.198347  4.132231  6.198347 14.462810 10.330579 10.330579
## [36] 30.991736 18.595041 16.528926 14.462810  4.132231 10.330579  8.264463
## [43]  6.198347 14.462810 14.462810 22.727273  8.264463 10.330579  0.000000
## [50]  6.198347  6.198347  0.000000  2.066116  0.000000  8.264463  6.198347
## [57]  2.066116  4.132231  4.132231  0.000000  4.132231  0.000000  0.000000
## [64]  2.066116  6.198347  2.066116  2.066116
## 
## $mids
##  [1] 0.0645 0.0655 0.0665 0.0675 0.0685 0.0695 0.0705 0.0715 0.0725 0.0735
## [11] 0.0745 0.0755 0.0765 0.0775 0.0785 0.0795 0.0805 0.0815 0.0825 0.0835
## [21] 0.0845 0.0855 0.0865 0.0875 0.0885 0.0895 0.0905 0.0915 0.0925 0.0935
## [31] 0.0945 0.0955 0.0965 0.0975 0.0985 0.0995 0.1005 0.1015 0.1025 0.1035
## [41] 0.1045 0.1055 0.1065 0.1075 0.1085 0.1095 0.1105 0.1115 0.1125 0.1135
## [51] 0.1145 0.1155 0.1165 0.1175 0.1185 0.1195 0.1205 0.1215 0.1225 0.1235
## [61] 0.1245 0.1255 0.1265 0.1275 0.1285 0.1295 0.1305
## 
## $xname
## [1] &quot;dat&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<p>to plot three different histograms of the <code>hidalgo</code> data set.</p>
<p>If you do this in SAS, write a macro that accepts a table name, a column name, a list of integers, a main axis label and an x axis label. This macro should scan over each element in the list of integers and produce a histogram for each integer value, setting the bin count to the element in the input list, and labeling main and x-axis with the specified parameters. You should label the y-axis to read <code>Frequency, bins =</code> and the number of bins.</p>
<p>Test your macro with the <code>hidalgo</code> data set (see below), using bin numbers 12, 36, and 60. You should be able to call your macro with something like</p>
<pre><code>%plot_histograms(hidalgo, y, 12 36 60, main=&quot;1872 Hidalgo issue&quot;, xlabel=&quot;Thickness (mm)&quot;);</code></pre>
<p>to plot three different histograms of the <code>hidalgo</code> data set.</p>
<p>Hint:
Assume <code>12 36 60</code> resolve to a single macro parameter and use <code>%scan</code>. Your macro definition can look something like</p>
<pre><code>%macro plot_histograms(table_name, column_name, number_of_bins, main=&quot;Main&quot;, xlabel=&quot;X Label&quot;)</code></pre>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>The <code>hidalgo</code> data set is in the file <code>hidalgo.dat</code> These data consist of paper thickness measurements of stamps from the 1872 Hidalgo issue of Mexico. This data set is commonly used to illustrate methods of determining the number of components in a mixture (in this case, different batches of paper). See <a href="https://www.jstor.org/stable/2290118" class="uri">https://www.jstor.org/stable/2290118</a>,<br />
<a href="https://books.google.com/books?id=1CuznRORa3EC&amp;lpg=PA95&amp;pg=PA94#v=onepage&amp;q&amp;f=false" class="uri">https://books.google.com/books?id=1CuznRORa3EC&amp;lpg=PA95&amp;pg=PA94#v=onepage&amp;q&amp;f=false</a> and <a href="https://books.google.com/books?id=c2_fAox0DQoC&amp;pg=PA180&amp;lpg=PA180&amp;f=false" class="uri">https://books.google.com/books?id=c2_fAox0DQoC&amp;pg=PA180&amp;lpg=PA180&amp;f=false</a>
.</p>
<p>Some analysis suggest there are three different mixtures of paper used to produce the 1872 Hidalgo issue; other analysis suggest seven. Why do you think there might be disagreement about the number of mixtures?</p>
<p>That is perhaps because of the uncontrollable variation
in paper thickness people used to have from sheet to sheet, we would expect more than three or seven mixtures, but in case of hidalgo, thickness was not that high. We can see in the histogram that the thickness was maintianed below 0.07 mm with highest frequency.</p>
</div>
</div>
<div id="exercise-5." class="section level1">
<h1>Exercise 5.</h1>
<p>We’ve been working with data from Wansink and Payne, Table 1:</p>
<div id="reproducing-part-of-wansink-table-1" class="section level3">
<h3>Reproducing part of Wansink Table 1</h3>
<table>
<colgroup>
<col width="16%" />
<col width="12%" />
<col width="12%" />
<col width="12%" />
<col width="12%" />
<col width="12%" />
<col width="12%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Measure</th>
<th align="right">1936</th>
<th align="right">1946</th>
<th align="right">1951</th>
<th align="right">1963</th>
<th align="right">1975</th>
<th align="right">1997</th>
<th align="right">2006</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">calories per recipe (SD)</td>
<td align="right">2123.8 (1050.0)</td>
<td align="right">2122.3 (1002.3)</td>
<td align="right">2089.9 (1009.6)</td>
<td align="right">2250.0 (1078.6)</td>
<td align="right">2234.2 (1089.2)</td>
<td align="right">2249.6 (1094.8)</td>
<td align="right">3051.9 (1496.2)</td>
</tr>
<tr class="even">
<td align="left">calories per serving (SD)</td>
<td align="right">268.1 (124.8)</td>
<td align="right">271.1 (124.2)</td>
<td align="right">280.9 (116.2)</td>
<td align="right">294.7 (117.7)</td>
<td align="right">285.6 (118.3)</td>
<td align="right">288.6 (122.0)</td>
<td align="right"><strong>384.4</strong> (168.3)</td>
</tr>
<tr class="odd">
<td align="left">servings per recipe (SD)</td>
<td align="right">12.9 (13.3)</td>
<td align="right">12.9 (13.3)</td>
<td align="right">13.0 (14.5)</td>
<td align="right">12.7 (14.6)</td>
<td align="right">12.4 (14.3)</td>
<td align="right">12.4 (14.3)</td>
<td align="right">12.7 (13.0)</td>
</tr>
</tbody>
</table>
<p>However, in Homework 2, we also considered the value given in the text</p>
<blockquote>
<p>The resulting increase of 168.8 calories (from 268.1 calories … to <strong>436.9</strong> calories …) represents a 63.0% increase … in calories per serving.</p>
</blockquote>
<p>There is a discrepancy between two values reported for calories per serving, 2006. We will use graphs to attempt to determine which value is most consistent.</p>
<p>First, consider the relationship between Calories per Serving and Calories per Recipe:</p>
<pre><code>Calories per Serving = Calories per Recipe / Servings per Recipe</code></pre>
<p>Since <code>Servings per Recipe</code> is effectively constant over time (12.4-13.0), we can assume the relationship between <code>Calories per Serving</code> and <code>Calories per Recipe</code> is linear,</p>
<p><span class="math display">\[
\text{Calories per Serving} = \beta_0 + \beta_1 \times \text{Calories per Recipe}
\]</span>
with <span class="math inline">\(\text{Servings per Recipe} = 1/\beta_1\)</span></p>
<p>We will fit a linear model, with <code>Calories per Recipe</code> as the independent variable against two sets of values for <code>Calories per Serving</code>, such that</p>
<ul>
<li>Assumption 1. The value in the table (<span class="math inline">\(384.4\)</span>) is correct.</li>
<li>Assumption 2. The value in the text (<span class="math inline">\(436.9\)</span>) is correct.</li>
</ul>
<p>We use the data:</p>
<pre class="r"><code>Assumptions.dat &lt;- data.frame(
  CaloriesPerRecipe = c(2123.8, 2122.3, 2089.9, 2250.0, 2234.2, 2249.6, 3051.9),
  Assumption1 = c(268.1, 271.1, 280.9, 294.7, 285.6, 288.6, 384.4),
  Assumption2 = c(268.1, 271.1, 280.9, 294.7, 285.6, 288.6, 436.9))</code></pre>
<p>and fit linear models</p>
<pre class="r"><code>Assumption1.lm &lt;- lm(Assumption1 ~ CaloriesPerRecipe,data=Assumptions.dat)
Assumption2.lm &lt;- lm(Assumption2 ~ CaloriesPerRecipe,data=Assumptions.dat)
summary(Assumption1.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Assumption1 ~ CaloriesPerRecipe, data = Assumptions.dat)
## 
## Residuals:
##       1       2       3       4       5       6       7 
## -7.0238 -3.8475  9.7610  4.7417 -2.5010 -1.3112  0.1808 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       25.477429  17.351550   1.468    0.202    
## CaloriesPerRecipe  0.117547   0.007466  15.745 1.88e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.163 on 5 degrees of freedom
## Multiple R-squared:  0.9802, Adjusted R-squared:  0.9763 
## F-statistic: 247.9 on 1 and 5 DF,  p-value: 1.879e-05</code></pre>
<pre class="r"><code>summary(Assumption2.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Assumption2 ~ CaloriesPerRecipe, data = Assumptions.dat)
## 
## Residuals:
##       1       2       3       4       5       6       7 
## -4.1798 -0.9169 14.5608  0.3051 -6.0261 -5.7248  1.9817 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -99.891018  21.933161  -4.554  0.00609 ** 
## CaloriesPerRecipe   0.175238   0.009437  18.569 8.34e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.79 on 5 degrees of freedom
## Multiple R-squared:  0.9857, Adjusted R-squared:  0.9828 
## F-statistic: 344.8 on 1 and 5 DF,  p-value: 8.336e-06</code></pre>
</div>
<div id="part-a." class="section level3">
<h3>Part a.</h3>
<p>Plot the regression. Use points to plot <code>Assumption1</code> vs <code>CaloriesPerRecipe</code>, and <code>Assumption2</code> vs <code>CaloriesPerRecipe</code>, on the same graph. Add lines (i.e. <code>abline</code>) to show the fit from the regression. Use different colors for the two assumptions. Which of the two lines appears to best explain the data?</p>
<pre class="r"><code>attach(Assumptions.dat)
par(mfrow=c(1,1))
plot(Assumption1~CaloriesPerRecipe, cex = 1.5, type = &#39;p&#39;, col = &#39;red&#39;)
abline(Assumption1.lm)
points(Assumption2~CaloriesPerRecipe, cex = 1.5, col = &#39;blue&#39;)
abline(Assumption2.lm)</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="part-b.-1" class="section level3">
<h3>Part b.</h3>
<p>Produce diagnostic plots plots of the residuals from both linear models (in R, use <code>residuals(Assumption1.lm)</code>). qqnorm or box-whisker plots will probably be the most effective; there are too few points for a histogram.</p>
<p>Use the code below to place two plots, side by side. You can produce more than one pair of plots, if you wise.</p>
<pre class="r"><code>par(mfrow=c(1,2))
boxplot(residuals(Assumption1.lm), main = &quot;Boxplot for Assumption1&quot; ) 
boxplot(residuals(Assumption2.lm), main = &quot;Boxplot for Assumption2&quot; )</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-14-1.png" width="768" /></p>
<pre class="r"><code>par(mfrow=c(1,2))
qqnorm(residuals(Assumption1.lm), main = &quot;QQplot for Assumption1&quot; )
qqline(residuals(Assumption1.lm))
qqnorm(residuals(Assumption2.lm), main = &quot;QQplot for Assumption2&quot; )
qqline(residuals(Assumption2.lm))</code></pre>
<p><img src="/achalneupane.github.io/post/Additional_Graphs_files/figure-html/unnamed-chunk-15-1.png" width="768" /></p>
<p>From these plots, which assumption is most likely correct. That is, which assumption produces a linear model that least violates assumptions of normality of the residual errors? Which assumption produces outliers in the residuals?</p>
<p>Answer: Based on the plots, assumption1 produces a more linear model that least violates assumption of normality of the residuals errors. Assumption2 produces the outlier/s.</p>
<p>I’ve included similar data and linear models for SAS in the SAS template. If you choose SAS, you will need to modify the PROC GLM code to produce the appropriate diagnostic plots.</p>
</div>
</div>

    </div>

    


    

<div class="article-tags">
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/r/">R</a>
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/statistics/">Statistics</a>
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/statistical_programming/">Statistical_programming</a>
  
</div>



    
      








  
  
    
  
  





  
  
  
  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/achalneupane.github.io/authors/achal-neupane/"></a></h5>
      
      
      <ul class="network-icon" aria-hidden="true">
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/achalneupane.github.io/post/final_assignment/">Final assignment</a></li>
          
          <li><a href="/achalneupane.github.io/post/midterm_project/">Midterm data analysis</a></li>
          
          <li><a href="/achalneupane.github.io/post/processing_text/">Processing text</a></li>
          
          <li><a href="/achalneupane.github.io/post/data_manipulation/">Data manipulation</a></li>
          
          <li><a href="/achalneupane.github.io/post/data_tables/">Data tables</a></li>
          
        </ul>
      </div>
      
    

    

    


  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
    

    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/achalneupane.github.io/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/achalneupane.github.io/js/academic.min.16bbb3750feb7244c9bc409a5a4fe678.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/achalneupane.github.io/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/achalneupane.github.io/terms/">Terms</a>
        
  </p>
  

  <p class="powered-by">
    © 2019 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
