<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.4.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Achal Neupane">

  
  
  
    
  
  <meta name="description" content="Instructions There are six exercises below. You are required to provide solutions for at least four of the five. You are required to solve at least one exercise in R, and at least one in SAS. You are required to provide five solutions, each solution will be worth 10 points. Thus, you may choose to provide both R and SAS solutions for a single exercise, or you may solve all five problems, mixing the languages as you wish.">

  
  <link rel="alternate" hreflang="en-us" href="/achalneupane.github.io/post/firstpost/">

  


  

  
  
  
  <meta name="theme-color" content="#3f51b5">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/achalneupane.github.io/css/academic.min.3072054fc61fe865aa34bcb366de141d.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-145752794-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/achalneupane.github.io/index.webmanifest">
  <link rel="icon" type="image/png" href="/achalneupane.github.io/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/achalneupane.github.io/img/icon-192.png">

  <link rel="canonical" href="/achalneupane.github.io/post/firstpost/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="twitter:site" content="@achalneupane">
  <meta property="twitter:creator" content="@achalneupane">
  
  <meta property="og:site_name" content="Achal Neupane">
  <meta property="og:url" content="/achalneupane.github.io/post/firstpost/">
  <meta property="og:title" content="Arrays | Achal Neupane">
  <meta property="og:description" content="Instructions There are six exercises below. You are required to provide solutions for at least four of the five. You are required to solve at least one exercise in R, and at least one in SAS. You are required to provide five solutions, each solution will be worth 10 points. Thus, you may choose to provide both R and SAS solutions for a single exercise, or you may solve all five problems, mixing the languages as you wish."><meta property="og:image" content="/achalneupane.github.io/img/icon-192.png">
  <meta property="twitter:image" content="/achalneupane.github.io/img/icon-192.png"><meta property="og:locale" content="en-us">
  
    
    
  

  


  





  <title>Arrays | Achal Neupane</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/achalneupane.github.io/">Achal Neupane</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#impact"><span>Impact</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/achalneupane.github.io/#contact"><span>Contact</span></a>
        </li>

        
        

      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article" itemscope itemtype="http://schema.org/Article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1 itemprop="name">Arrays</h1>

  

  
    



<meta content="" itemprop="datePublished">
<meta content="" itemprop="dateModified">

<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    <time>Jan 1, 0001</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    34 min read
  </span>
  

  
  
  

  
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/achalneupane.github.io/post/firstpost/&amp;text=Arrays" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/achalneupane.github.io/post/firstpost/&amp;t=Arrays" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Arrays&amp;body=/achalneupane.github.io/post/firstpost/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/achalneupane.github.io/post/firstpost/&amp;title=Arrays" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Arrays%20/achalneupane.github.io/post/firstpost/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/achalneupane.github.io/post/firstpost/&amp;title=Arrays" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
<div id="instructions" class="section level1">
<h1>Instructions</h1>
<p>There are six exercises below. You are required to provide solutions for at least four of the five. You are required to solve at least one exercise in R, and at least one in SAS. You are required to provide five solutions, each solution will be worth 10 points. Thus, you may choose to provide both R and SAS solutions for a single exercise, or you may solve all five problems, mixing the languages as you wish. The first four exercise refer to formula from the previous homework, you may reuse code as you wish.</p>
<div id="experimental" class="section level4">
<h4>Experimental</h4>
<p>Again, you will be allowed to provide one solution using Python. Elaborate on the similarities and differences between Python arrays vs R or IML.</p>
</div>
</div>
<div id="exercise-1." class="section level1">
<h1>Exercise 1.</h1>
<div id="part-a." class="section level3">
<h3>Part a.</h3>
<p>We will calculate a number of required replicates for a range of mean differences, comparable to calories per serving estimates found in Wansink, Table 1.</p>
<p>Let <span class="math inline">\(m_1\)</span> be a sequence of means from 320-420, incremented by 10. Let <span class="math inline">\(m_2\)</span> be 270. Assume a pooled standard deviation of 150.</p>
<p>Calculate Cohen’s <span class="math inline">\(d\)</span> for the pairs of means <span class="math inline">\({320 - 270, 330 - 270, ...., 420 - 270}\)</span>, letting <span class="math inline">\(s_i = s_j = s_{pooled}\)</span>. Calculate the required replicates for these same pairs of means. You may reuse code or functions from previous homework at your discretion.</p>
<p>To show your results, either create and print a matrix with one colum for effect size and one column for replicates, or plot required replicates versus effect size (effect size will be the independent variable). What does this tell you about the number of observations required to detect medium-size effects? You may include reference lines in your plot to illustrate.</p>
<p>Since we know that <span class="math inline">\(s_{pooled} = \sqrt{(s_1^2 + s_2^2)/2}\)</span></p>
<pre class="r"><code># Creating a function with constant m2, pooled sd, alpha and beta.
combined &lt;- function (m1,m2 = 270, s_pooled = 150, alpha = 0.05, beta = 0.2){
  cv &lt;- (s_pooled)/((m1+m2)/2)
  percent.diff &lt;- ((m1-m2)/((m1+m2)/2))
  cohens_d &lt;-(abs(m1-m2)/(s_pooled))
  n &lt;- 2*(((cv/percent.diff)^2)*(qnorm((1-alpha/2)) + qnorm((1-beta)))^2) 
  n &lt;- round(n,0)
  value &lt;- (list(CV = cv, PercentDiff= percent.diff, RequiredReplicates = round(n,0), EffectSize = cohens_d))
  return(value)
  }


m1 &lt;- seq(320,420,10)
m1</code></pre>
<pre><code>##  [1] 320 330 340 350 360 370 380 390 400 410 420</code></pre>
<pre class="r"><code>data &lt;- combined(m1 = m1)
# cal.lm &lt;- lm(data$RequiredReplicates ~ data$EffectSize)
# or even quadratic term
# cal.lm &lt;- lm(data$RequiredReplicates ~ poly(data$EffectSize, 3, raw = TRUE))
plot(data$EffectSize, data$RequiredReplicates)
# abline(cal.lm)
# As per rule of thumb for medium-size effect, we can choose v= 0.5 as medium-size effects
# http://staff.bath.ac.uk/pssiw/stats2/page2/page14/page14.html
# Also, http://staff.bath.ac.uk/pssiw/stats2/page2/page14/page14.html
abline(v = 0.5, col= &#39;red&#39;)</code></pre>
<p><img src="/achalneupane.github.io/post/firstpost_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Note: Cohen suggested that d = 0.2 be considered a ‘small’ effect size, 0.5 represents a ‘medium’ effect size and 0.8 a ‘large’ effect size. This means that if two groups’ means don’t differ by 0.2 standard deviations or more, the difference is trivial, even if it is statistically signficant. This plot tells us that with the increasing effect-size, we need fewer replicates. Since effect-size of |0.5| or (v= 0.5) is intersects with the abline at approximately 78 replicates in the plot, it also tells us that for medium-size effect we need about 78 replicates.</p>
</div>
</div>
<div id="exercise-2" class="section level1">
<h1>Exercise 2</h1>
<p>Create a table to show the required replicates for a range of combinations of <span class="math inline">\(\%Diff\)</span> and <span class="math inline">\(CV\)</span>. Do this in steps as follows:</p>
<div id="part-a.-1" class="section level3">
<h3>Part a.</h3>
<p>Define two matrices, one for <code>CV</code> and one for <code>Diff</code>. Each will matrix will be 5 rows by 6 columns. Let the rows in CV be the sequence <span class="math inline">\(8, 12, ..., 28\)</span> and let the columns of <code>Diff</code> be the squence <span class="math inline">\(5,10, ... , 25\)</span>. The matrices should look like:</p>
<p><span class="math display">\[
\begin{aligned} 
 CV &amp; = \left\{
 \begin{array}{cccccc}
     8 &amp; 12 &amp; 16 &amp; 20 &amp; 24 &amp; 28  \\
     8 &amp; 12 &amp; 16 &amp; 20 &amp; 24 &amp; 28  \\
     \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots  &amp; \vdots \\
     8 &amp; 12 &amp; 16 &amp; 20 &amp; 24 &amp; 28  \\
   \end{array}
   \right\} \\
   &amp; \\
 \%Diff &amp; = \left\{
 \begin{array}{ccccc}
     5 &amp; 5 &amp; 5 &amp; 5 &amp; 5  \\
     10 &amp; 10 &amp; 10 &amp; 10 &amp; 10 \\
     \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots \\
     25 &amp; 25 &amp; 25 &amp; 25 &amp; 25 \\
   \end{array}
   \right\}
\end{aligned} 
\]</span></p>
<p>Define and print your matrices in the code below.</p>
<pre class="r"><code># create sequence data and then matrix for CV
rep.cv &lt;- rep(seq(8,28,4),5)
rep.cv</code></pre>
<pre><code>##  [1]  8 12 16 20 24 28  8 12 16 20 24 28  8 12 16 20 24 28  8 12 16 20 24
## [24] 28  8 12 16 20 24 28</code></pre>
<pre class="r"><code>cv &lt;- matrix(rep.cv, nrow = 5, ncol = 6, byrow = TRUE)
cv</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    8   12   16   20   24   28
## [2,]    8   12   16   20   24   28
## [3,]    8   12   16   20   24   28
## [4,]    8   12   16   20   24   28
## [5,]    8   12   16   20   24   28</code></pre>
<pre class="r"><code># create sequence data and then matrix for %Diff
rep.Diff &lt;- rep(seq(5,25,5), 6)
rep.Diff</code></pre>
<pre><code>##  [1]  5 10 15 20 25  5 10 15 20 25  5 10 15 20 25  5 10 15 20 25  5 10 15
## [24] 20 25  5 10 15 20 25</code></pre>
<pre class="r"><code>Diff &lt;- matrix(rep.Diff, nrow = 5, ncol = 6, byrow = FALSE)
Diff</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]    5    5    5    5    5    5
## [2,]   10   10   10   10   10   10
## [3,]   15   15   15   15   15   15
## [4,]   20   20   20   20   20   20
## [5,]   25   25   25   25   25   25</code></pre>
</div>
<div id="part-b." class="section level3">
<h3>Part b.</h3>
<p>Calculate require replicates for each combination of <code>CV</code> and <code>Diff</code>. Use the same values for <span class="math inline">\(z_\alpha\)</span> and <span class="math inline">\(z_\beta\)</span> as from Homework 2 and 3. You should be able to reuse coce from previous exercises, and you should not use iteration.</p>
<p>Print the result below. The result should be a <span class="math inline">\(5 \times 6\)</span> matrix.</p>
<pre class="r"><code># Now vectorize the matrices CV and %Diff from above
cv.vector &lt;- as.vector(cv) 
cv.vector</code></pre>
<pre><code>##  [1]  8  8  8  8  8 12 12 12 12 12 16 16 16 16 16 20 20 20 20 20 24 24 24
## [24] 24 24 28 28 28 28 28</code></pre>
<pre class="r"><code>Diff.vector &lt;- as.vector(Diff)
Diff.vector</code></pre>
<pre><code>##  [1]  5 10 15 20 25  5 10 15 20 25  5 10 15 20 25  5 10 15 20 25  5 10 15
## [24] 20 25  5 10 15 20 25</code></pre>
<pre class="r"><code># We can then use the function in exercise 1 by slightly modifying it as:
combined &lt;- function (cv, percent.diff, alpha = 0.05, beta = 0.2){
  cv &lt;- cv
  percent.diff &lt;- percent.diff
  n &lt;- 2*(((cv/percent.diff)^2)*(qnorm((1-alpha/2)) + qnorm((1-beta)))^2) 
  n &lt;- round(n,0)
  value &lt;- list(CV = cv, PercentDiff= percent.diff, RequiredReplicates = round(n,0))
  return(value)
}
value &lt;- combined(cv = cv.vector, percent.diff = Diff.vector)

RequiredReplicates &lt;- matrix(value$RequiredReplicates, nrow = 5, ncol = 6, byrow = FALSE)
RequiredReplicates</code></pre>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]   40   90  161  251  362  492
## [2,]   10   23   40   63   90  123
## [3,]    4   10   18   28   40   55
## [4,]    3    6   10   16   23   31
## [5,]    2    4    6   10   14   20</code></pre>
<p>To check your work, repeat the calculations using the rule of thumb from the previous exercises. What is largest deviation of the rule of thumb from the exact calculation?</p>
<p>For this, first we can simplify the equations as follows:
first for CV,</p>
<p><span class="math inline">\(CV = \frac{sd_{pooled}}{(m_1 + m_2)/2}\)</span>
<span class="math inline">\((m_1 + m_2)/2) = \frac{sd_{pooled}}{CV/2}\)</span>
<span class="math inline">\((m_1 + m_2)/2) = {2} \times\frac{sd_{pooled}}{CV}\)</span></p>
<p>then, for <span class="math inline">\(\%diff\)</span>:</p>
<p><span class="math inline">\(\%Diff = \frac{m_1 - m_2}{(m_1 + m_2)/2}\)</span>
<span class="math inline">\(\%Diff\times\frac{(m_1 + m_2)}{2} = m_1-m_2\)</span>
<span class="math inline">\(m_1-m_2 = \frac{\%Diff}{2}\times(m_1 + m_2)\)</span></p>
<p>Now, if we replace <span class="math inline">\(m_1 + m_2\)</span>, we get:
<span class="math inline">\(m_1-m_2 = \frac{\%Diff}{2}\times ({2} \times\frac{sd_{pooled}}{CV})\)</span></p>
<p>Or, <span class="math inline">\(m_1-m_2 = \frac{{\%Diff } \ \times\ {sd_{pooled}}}{CV}\)</span></p>
<p>This will give us delta (<span class="math inline">\(\triangle\)</span>):
<span class="math inline">\(\triangle = \frac{m_1-m_2}{sd_{pooled}} = \frac{1}{sd_{pooled}} \times \frac{{\%Diff } \ \times\ {sd_{pooled}}}{CV} = \frac{\%Diff}{CV}\)</span></p>
<p>Now we can use, rule of thumb as:
<span class="math inline">\(n = \frac{16}{\triangle^2}\)</span></p>
<pre class="r"><code># As stated in rule of thumb: http://www.nrcse.washington.edu/research/struts/chapter2.pdf
# We can then use the simplified equation
rule.of.thumb.n &lt;- function (cv, percent.diff){
  cv &lt;- cv
  percent.diff &lt;- percent.diff
  delta &lt;- percent.diff/cv
  n &lt;- (16/(delta^2))
  value &lt;- list(CV = cv, PercentDiff= percent.diff, RequiredReplicates = round(n,0))
  return(value)
}

value &lt;- rule.of.thumb.n(cv= cv.vector, percent.diff = Diff.vector)
Rule.of.Thumb.matrix &lt;- matrix(value$RequiredReplicates, nrow = 5, ncol = 6, byrow = FALSE)
colnames(Rule.of.Thumb.matrix) &lt;- paste0(&quot;CV&quot;,unique(value$CV))
rownames(Rule.of.Thumb.matrix) &lt;- paste0(&quot;Diff&quot;,unique(value$PercentDiff))
# This matrix gives you the combination of all pairs of CV and %Diff for rule of thumb
Rule.of.Thumb.matrix</code></pre>
<pre><code>##        CV8 CV12 CV16 CV20 CV24 CV28
## Diff5   41   92  164  256  369  502
## Diff10  10   23   41   64   92  125
## Diff15   5   10   18   28   41   56
## Diff20   3    6   10   16   23   31
## Diff25   2    4    7   10   15   20</code></pre>
<pre class="r"><code># We can then compare the matrix from exact calculation and required replicates
# calculated using rule of thumb method by calculating the percent difference of
# two data matrices
percent_difference_between_two_df &lt;- data.frame((abs(RequiredReplicates-Rule.of.Thumb.matrix)/(abs(RequiredReplicates+Rule.of.Thumb.matrix)/2))*100)
percent_difference_between_two_df</code></pre>
<pre><code>##                   CV8         CV12           CV16          CV20
## Diff5   2.46913580247 2.1978021978  1.84615384615 1.97238658777
## Diff10  0.00000000000 0.0000000000  2.46913580247 1.57480314961
## Diff15 22.22222222222 0.0000000000  0.00000000000 0.00000000000
## Diff20  0.00000000000 0.0000000000  0.00000000000 0.00000000000
## Diff25  0.00000000000 0.0000000000 15.38461538462 0.00000000000
##                 CV24          CV28
## Diff5  1.91518467852 2.01207243461
## Diff10 2.19780219780 1.61290322581
## Diff15 2.46913580247 1.80180180180
## Diff20 0.00000000000 0.00000000000
## Diff25 6.89655172414 0.00000000000</code></pre>
<p>Therefore, %Diff of 15 and CV of 8 has the highest deviation of 22.22% between calculated vs rule of thumb method for required replicates.</p>
</div>
</div>
<div id="exercise-3" class="section level1">
<h1>Exercise 3</h1>
<p>In this exercise, we’ll use your <code>norm.pdf</code> function to illustrate how the formula for required replicates finds a compromise between Type I and Type II error rates. This is also a way to test your normal probability function over a range of arguments.</p>
<p><strong>Do not print the vectors you create for this exercise in the final typeset submission</strong> We will check the results by examining the plots, and printing the vectors themselves will unnecessarily clutter your report. If you get stuck, use the built normal functions to create your plots.</p>
<div id="part-a.-2" class="section level3">
<h3>Part a.</h3>
<p>Generate a squence of values from <span class="math inline">\(-3,...,4\)</span> incremented by <span class="math inline">\(0.1\)</span>; let this be <code>x</code>.
Calculate the probability of each value of <code>x</code> using the <code>norm.pdf</code> function from Homework 3, letting <code>mu = 0</code> and <code>sd = 1</code>. Name the result <code>p.null</code>.</p>
<p>Calculate the effect size for 1936 versus 2006, calories per serving, as in Homework 2 and 3. Repeat the calculation for the probability of <code>x</code>, but this time use <code>mean=</code> effect size. Name this result <code>p.alt</code>.</p>
<p>The results will be the distribution of the expected value of the difference between means; the first is the expectation under the null hypothesis (the true effect size is 0) while the second is the expectation assuming the measured <span class="math inline">\(d\)</span> is the true <span class="math inline">\(d\)</span>.</p>
<pre class="r"><code># Function to calcuate the values for log liklihood.
# First, we define the values for sigma as variance, 
# mu as mean of a normal population to be used for a liklihood of a x observation.
norm.pdf &lt;- function(x,mu = 0,sigma = 1){
  l&lt;-1/(sigma*sqrt(pi*2))*exp(-((x-mu)^2)/(2*sigma^2))
  return(l)
}

x &lt;- seq(-3, 4, 0.1)
p.null &lt;- norm.pdf(x)

#calculating effect size to be used as &#39;mean= &#39; for the analysis below
combined &lt;- function (m1,m2,s1,s2, alpha = 0.05, beta = 0.2){
  cohens_d &lt;-(abs(m1-m2)/sqrt((s1^2+s2^2)/2))
  value &lt;- (list(EffectSize = cohens_d))
}

#calculate the effect size for 1936 vs 2006, calories per serving
m1 = 268.1
m2 = 384.4
s1 = 124.8
s2 = 168.3
value &lt;- combined(m1 = m1, m2 = m2, s1 = s1, s2 = s2)
value$EffectSize</code></pre>
<pre><code>## [1] 0.784987603959</code></pre>
<pre class="r"><code># now repeating the calculation 
mean = value$EffectSize
mean</code></pre>
<pre><code>## [1] 0.784987603959</code></pre>
<pre class="r"><code>p.alt &lt;- norm.pdf(x, mu = mean)</code></pre>
</div>
<div id="part-b.-1" class="section level3">
<h3>Part b.</h3>
<p>Repeat the calculations of <code>p.null</code> and <code>p.alt</code>, but this time let <code>sigma =</code> <span class="math inline">\(\sqrt{2/n}\)</span> where <span class="math inline">\(n = 10\)</span>. Name these <code>p.null.10</code> and <code>p.alt.10</code>. These calculations narrow the distribbutions by an amount proportional to standard error.</p>
<pre class="r"><code>n &lt;- 10
norm.pdf &lt;- function(x, n, mu = 0){
  sigma = (sqrt(2/n))
  l&lt;-1/(sigma*sqrt(pi*2))*exp(-((x-mu)^2)/(2*sigma^2))
  return(l)
}

x &lt;- seq(-3, 4, 0.1)
p.null.10 &lt;- norm.pdf(x = x, n = n)

mean = value$EffectSize
mean</code></pre>
<pre><code>## [1] 0.784987603959</code></pre>
<pre class="r"><code>p.alt.10 &lt;- norm.pdf(x = x, n = n, mu = mean)</code></pre>
</div>
<div id="part-c." class="section level3">
<h3>Part c.</h3>
<p>Repeat the calculations of <code>p.null</code> and <code>p.alt</code>, but this time let <code>sigma =</code> <span class="math inline">\(\sqrt{2/n}\)</span> where <span class="math inline">\(n\)</span> is the minimun mumber of replicates for calories per recipe, 1936 versus 2006, as calculated previously. Call these <code>p.null.req</code> and <code>p.alt.req</code>.</p>
<pre class="r"><code># Re-using the function to calculate minimum required replicates
required.replicates &lt;- function (m1,m2, s1,s2, alpha = 0.05, beta = 0.2){
  n &lt;- 2* ((((sqrt((s1^2 + s2^2)/2))/(m1-m2))^2) * (qnorm((1-alpha/2)) + qnorm((1-beta)))^2) 
  return(round(n,0))
}

m1 = 268.1
m2 = 384.4
s1 = 124.8
s2 = 168.3

n &lt;- required.replicates(m1 = m1, m2 = m2, s1 = s1, s2 = s2)
n.min.replicates &lt;- n
n.min.replicates</code></pre>
<pre><code>## [1] 25</code></pre>
<pre class="r"><code>norm.pdf &lt;- function(x, n, mu = 0){
  sigma = (sqrt(2/n))
  l&lt;-1/(sigma*sqrt(pi*2))*exp(-((x-mu)^2)/(2*sigma^2))
  return(l)
}

x &lt;- seq(-3, 4, 0.1)
p.null.req &lt;- norm.pdf(x = x, n = n)


mean = value$EffectSize
mean</code></pre>
<pre><code>## [1] 0.784987603959</code></pre>
<pre class="r"><code>p.alt.req &lt;- norm.pdf(x = x, n = n, mu = mean)</code></pre>
</div>
<div id="part-d." class="section level3">
<h3>Part d.</h3>
<p>Plot <code>p.null</code> versus <code>x</code> as a black line and in the same plot add <code>p.alt</code> vs <code>x</code> as a red line. Add a green vertical line at <span class="math inline">\(z_\alpha\)</span> and a blue vertical line at <span class="math inline">\(z_\beta\)</span>, using values as in previous exercises. The green line represents the critical value for Type I error, and the error under the black curve to the left of the green line is the probability of that error (97.5%). The area under the red curve, to the left of the green line, represents the achieved Type II error rate, the blue line represents the desired Type II rate.</p>
<p>Repeat the plot with <code>p.null.10</code> and <code>p.alt.10</code>, but this time add vertical lines at <span class="math inline">\(z_\alpha \times \sqrt{2/10}\)</span> and at <span class="math inline">\(z_\beta \times \sqrt{2/10}\)</span>. The lines representing critical values for Type I and Type II error should move closer as the distributions narrow.</p>
<p>Repeat the plot with <code>p.null.req</code> and <code>p.alt.req</code>, but this time add vertical lines at <span class="math inline">\(z_\alpha \times \sqrt{2/n}\)</span> and at <span class="math inline">\(z_\beta \times \sqrt{2/n}\)</span>, where <span class="math inline">\(n\)</span> is the minimum replicates. Do the lines for Type I and Type II error overlap?</p>
<p>It will improve the readability of the three plots if you plot all three in the chunk below. The arguments inside the braces specify the dimensions of the plot, while <code>par(mfrow = c(3,1))</code> combines three plots into one graph.</p>
<pre class="r"><code>par(mfrow = c(3,1))
# using base plot function part A
alpha = 0.05; beta = 0.2
Zalpha &lt;- qnorm(1-alpha/2)
Zbeta &lt;- qnorm(1-beta)
plot(x,p.null,type=&quot;l&quot;,col=&quot;black&quot;)
lines(x,p.alt,col=&quot;red&quot;)
abline(v = Zalpha, col= &#39;green&#39;)
abline(v = value$EffectSize-Zbeta, col= &#39;blue&#39;)

### using ggplot
# plot1 &lt;- ggplot()+
#   geom_line(aes(x = x, y = p.null), color = &quot;black&quot; ) +
#   geom_line(aes(x = x, y =  p.alt), color = &quot;red&quot;) +
#   geom_vline(xintercept = Zalpha, color = &quot;green&quot;)+
#   geom_vline(xintercept = value$EffectSize - Zbeta, color = &quot;blue&quot;)
# plot1

# using base plot function Part B
alpha = 0.05; beta = 0.2; n &lt;- 10
Zalpha &lt;- qnorm(1-alpha/2)
Zalpha &lt;- Zalpha * sqrt(2/n)
Zbeta &lt;- qnorm(1-beta)
Zbeta &lt;- Zbeta * sqrt(2/n)
plot(x,p.null.10,type=&quot;l&quot;,col=&quot;black&quot;)
lines(x,p.alt.10,col=&quot;red&quot;)
abline(v = Zalpha, col= &#39;green&#39;)
abline(v = (value$EffectSize-Zbeta), col= &#39;blue&#39;)

## Using ggplot
# plot2 &lt;- ggplot()+
#   geom_line(aes(x = x, y = p.null.10), color = &quot;black&quot; ) +
#   geom_line(aes(x = x, y =  p.alt.10), color = &quot;red&quot;) +
#   geom_vline(xintercept = Zalpha, color = &quot;green&quot;) +
#   geom_vline(xintercept = value$EffectSize - Zbeta, color = &quot;blue&quot;)
# plot2

# using base plot function Part C
alpha = 0.05; beta = 0.2; n &lt;- n.min.replicates
Zalpha &lt;- qnorm(1-alpha/2)
Zalpha &lt;- Zalpha * sqrt(2/n)
Zbeta &lt;- qnorm(1-beta)
Zbeta &lt;- Zbeta * sqrt(2/n)
plot(x,p.null.req,type=&quot;l&quot;,col=&quot;black&quot;)
lines(x,p.alt.req,col=&quot;red&quot;)
abline(v = Zalpha, col= &#39;green&#39;)
abline(v = value$EffectSize-Zbeta, col= &#39;blue&#39;)</code></pre>
<p><img src="/achalneupane.github.io/post/firstpost_files/figure-html/unnamed-chunk-9-1.png" width="576" /></p>
<pre class="r"><code>## Using ggplot
# plot3 &lt;- ggplot()+
#   geom_line(aes(x = x, y = p.null.req), color = &quot;black&quot; ) +
#   geom_line(aes(x = x, y =  p.alt.req), color = &quot;red&quot;) +
#   geom_vline(xintercept = Zalpha, color = &quot;green&quot;) +
#   geom_vline(xintercept = value$EffectSize - Zbeta, color = &quot;blue&quot;)
# plot3

# # Then merge all ggplots:
# library(grid)
# library(gridExtra)
# grid.newpage()
# grid.draw(arrangeGrob(plot1, plot2, plot3, heights = c(1/3, 1/3, 1/3)) )</code></pre>
<p>Here, The lines representing critical values for Type I and Type II error move closer as the distributions narrow. Yes, the lines for Type I and Type II error overlap.</p>
<p>Note: z_beta should be plotted relative to the alternative hypothesis value (in this case, d), since z_beta is the critical value to control for Type II error, where we would (fail to reject)* the null hypothesis and miss a true effect. Thus, the line for z_beta needs to be plotted relative to d, and it needs to be offset to the left, so you should be plotting a line at d-z_beta, etc. The alternative hypothesis is that the effect size we measured, d, is the true effect size.
Perhaps another way to phrase this is, the right-hand distribution illustrates values of the true effect size d that are consistent with a measured effect size. There’s a big debate in statistics on the use of null hypothesis tests. Perhaps a better visualization would be to demonstrate how narrowing the distributions (2, 10, n) changes likelihood ratio or Bayes factor.</p>
<p>If you choose to solve this with SAS, I’ve included code in the SAS template to create the graphs, since combining plots in IML is not as easy as in R.</p>
</div>
</div>
<div id="exercise-4" class="section level1">
<h1>Exercise 4</h1>
<p>In this, we compare the normal and Poisson distributions, using the functions you’ve written previously. This is also a way to test your normal and Poisson functions over a range of arguments.</p>
<p><strong>Do not print the vectors you create for this exercise in the final typeset submission</strong> We will check the results by examining the plots, and printing the vectors themselves will unnecessarily clutter your report. If you get stuck, use the built functions to create your plots. However, the final submission must call your functions.</p>
<div id="part-a" class="section level3">
<h3>Part a</h3>
<p>Create a sequence of <span class="math inline">\(x_a\)</span> from <span class="math inline">\(( -5 ... 5 )\)</span>, incremented by 0.1. Calculate the normal likelihood for each <span class="math inline">\(x\)</span>, assuming <span class="math inline">\(\mu = 0\)</span> and <span class="math inline">\(\sigma = 1\)</span>. Also calculate Poisson probability of each <span class="math inline">\(x\)</span> given a <code>lambda = 1</code>.</p>
<p>NOTE: The Poisson parameter Lambda (λ) is the total number of events (k) divided by the number of units (n) in the data (λ = k/n)</p>
<p>Plot both sets of probablities against <code>x</code> as lines, using a different color for each curve. Make sure that both curves fit in the plot; you may need to determine minimum and maximum values and set these as graphic parameters (see <code>ylim</code>).</p>
<p>Warning: if you do this in SAS, you may have to adjust the lower bound of <span class="math inline">\(x\)</span>.</p>
<pre class="r"><code># Suppressing warnings that may be generated by Poisson function for negative values
# options(warn=-1)

x_a &lt;- seq(-5, 5, 0.1)
x_a</code></pre>
<pre><code>##   [1] -5.0 -4.9 -4.8 -4.7 -4.6 -4.5 -4.4 -4.3 -4.2 -4.1 -4.0 -3.9 -3.8 -3.7
##  [15] -3.6 -3.5 -3.4 -3.3 -3.2 -3.1 -3.0 -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3
##  [29] -2.2 -2.1 -2.0 -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.0 -0.9
##  [43] -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.0  0.1  0.2  0.3  0.4  0.5
##  [57]  0.6  0.7  0.8  0.9  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9
##  [71]  2.0  2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3
##  [85]  3.4  3.5  3.6  3.7  3.8  3.9  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7
##  [99]  4.8  4.9  5.0</code></pre>
<pre class="r"><code>norm.pdf &lt;- function(x,mu=0,sigma=1){
  l&lt;-1/(sigma*sqrt(pi*2))*exp(-((x-mu)^2)/(2*sigma^2))
  return(l)
}
normal.liklihood.x_a &lt;- norm.pdf(x_a)


# The function to calculate probability mass function for poisson 
# data with a mean and variance lambda = 1. 
pois.pmf &lt;- function(x, lambda){
  poisson.d &lt;- exp(-lambda)*(1/(factorial(round(x,0))))*exp(round(x,0)*(log(lambda)))
  return(poisson.d)
}
lambda &lt;- 1
poisson.probability.x_a &lt;- pois.pmf(x=x_a, lambda = lambda)</code></pre>
<pre><code>## Warning in gamma(x + 1): NaNs produced</code></pre>
<pre class="r"><code>plot(x_a,normal.liklihood.x_a,type=&quot;l&quot;,col=&quot;black&quot;)
lines(x_a,poisson.probability.x_a,col=&quot;red&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/firstpost_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Does this graph tell you if your Normal PDF function behaves properly? Does your Poisson handle negative or non-integer values as expected?</p>
<p>No, based on this plot, the normal pdf does behave properly, but not the poisson as there NAs inserted for negative and non-integer values.</p>
</div>
<div id="part-b" class="section level3">
<h3>Part b</h3>
<p>Create a sequence of <span class="math inline">\(x_b = \left \lfloor{\mu - 5 \times \sigma } \right \rfloor , \dots, \left \lceil{\mu+ 5 \times \sigma } \right \rceil\)</span> using mean and standard deviation for servings per recipe from 1936.</p>
<p>Calculate the normal and Poission probability for each <span class="math inline">\(x\)</span> as in part a, again using mean and standard deviation from servings per recipe, 1936. The length of this vector should be the same length as the <span class="math inline">\(x\)</span> vector as in part a (<span class="math inline">\(\pm 1\)</span>), so you will need to calculate an interval based on the range <code>x_b</code> and the number of elements in <code>x_a</code></p>
<p>Show the the length of both <span class="math inline">\(x\)</span> vectors are similar by calling <code>length</code> for each.</p>
<p>Repeat the plot from part a with this sequence.</p>
<p>If you choose to solve this with SAS, I’ve included code in the SAS template to create the graphs, since combining plots in IML is not as easy as in R.</p>
<pre class="r"><code># Using mean and standard deviation for servings per recipe from 1936:
mu = 12.9; sigma = 13.3

# Now we find the upper and lower bounds as:
x.lower &lt;- floor(mu-5*sigma)
x.upper &lt;- ceiling(mu+5*sigma)

# Now taking the length of x_a as a reference, we create the equeally spaced
# sequence from lower to upper bound as followed:
spacer &lt;- (x.upper - x.lower)/(length(x_a) - 1)

x_b &lt;- seq(x.lower, x.upper, spacer)
# To show both x_a and x_b &#39;s lenghts are equal:
length(x_a)</code></pre>
<pre><code>## [1] 101</code></pre>
<pre class="r"><code>length(x_b)</code></pre>
<pre><code>## [1] 101</code></pre>
<pre class="r"><code>norm.pdf &lt;- function(x, mu = 12.9, sigma = 13.3){
  l&lt;-1/(sigma*sqrt(pi*2))*exp(-((x-mu)^2)/(2*sigma^2))
  return(l)
}
normal.liklihood.x_b &lt;- norm.pdf(x_b)


# The function to calculate probability mass function for poisson 
# data with a mean and variance lambda = 12. 
pois.pmf &lt;- function(x, lambda){
  poisson.d &lt;- exp(-lambda)*(1/(factorial(round(x,0))))*exp(round(x,0)*(log(lambda)))
  return(poisson.d)
}

#using sigma = 13.3 to compare the difference with the first plot
poisson.probability.x_b &lt;- pois.pmf(x=x_b, lambda = 12)</code></pre>
<pre><code>## Warning in gamma(x + 1): NaNs produced</code></pre>
<pre class="r"><code># plot
plot(x_b,normal.liklihood.x_b,type=&quot;l&quot;,col=&quot;black&quot;)
lines(x_b,poisson.probability.x_b,col=&quot;red&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/firstpost_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>To check you work, duplicate the plots by calling built in normal and Poisson functions. Does the system Poisson function handle negative <span class="math inline">\(x\)</span> differently than your function?</p>
<pre class="r"><code># Using base functions for part a  
base.normal.liklihood.x_a &lt;- dnorm(x_a,0, 1)
base.poiss.x_a &lt;- dpois(x=x_a, lambda = lambda)</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -4.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -3.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -2.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -1.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = -0.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 0.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 1.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 2.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 3.900000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.100000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.200000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.300000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.400000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.500000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.600000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.700000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.800000</code></pre>
<pre><code>## Warning in dpois(x = x_a, lambda = lambda): non-integer x = 4.900000</code></pre>
<pre class="r"><code>plot(x_a,base.normal.liklihood.x_a,type=&quot;l&quot;,col=&quot;black&quot;)
lines(x_a,base.poiss.x_a,col=&quot;red&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/firstpost_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code># Using base functions for part b
base.normal.liklihood.x_b &lt;- dnorm(x_b,0, 1)
base.poiss.x_b &lt;- dpois(x=x_b, lambda = 12)</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -52.660000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -51.320000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -49.980000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -48.640000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -47.300000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -45.960000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -44.620000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -43.280000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -41.940000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -40.600000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -39.260000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -37.920000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -36.580000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -35.240000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -33.900000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -32.560000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -31.220000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -29.880000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -28.540000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -27.200000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -25.860000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -24.520000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -23.180000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -21.840000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -20.500000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -19.160000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -17.820000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -16.480000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -15.140000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -13.800000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -12.460000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -11.120000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -9.780000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -8.440000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -7.100000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -5.760000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -4.420000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -3.080000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -1.740000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = -0.400000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 0.940000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 2.280000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 3.620000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 4.960000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 6.300000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 7.640000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 8.980000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 10.320000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 11.660000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 14.340000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 15.680000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 17.020000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 18.360000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 19.700000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 21.040000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 22.380000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 23.720000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 25.060000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 26.400000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 27.740000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 29.080000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 30.420000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 31.760000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 33.100000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 34.440000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 35.780000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 37.120000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 38.460000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 39.800000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 41.140000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 42.480000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 43.820000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 45.160000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 46.500000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 47.840000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 49.180000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 50.520000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 51.860000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 53.200000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 54.540000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 55.880000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 57.220000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 58.560000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 59.900000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 61.240000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 62.580000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 63.920000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 65.260000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 66.600000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 67.940000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 69.280000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 70.620000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 71.960000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 73.300000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 74.640000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 75.980000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 77.320000</code></pre>
<pre><code>## Warning in dpois(x = x_b, lambda = 12): non-integer x = 78.660000</code></pre>
<pre class="r"><code>plot(x_b,base.normal.liklihood.x_b,type=&quot;l&quot;,col=&quot;black&quot;)
lines(x_b,base.poiss.x_b,col=&quot;red&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/firstpost_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p>Yes, the system Poisson function handles negative values and non-integers differently (inserts zero’s) whereas the function we wrote inserts NAs for negative and non-integer values.</p>
</div>
</div>
<div id="exercise-5" class="section level1">
<h1>Exercise 5</h1>
<p>Consider the table:</p>
<table>
<thead>
<tr class="header">
<th>Rate</th>
<th>23000</th>
<th>24000</th>
<th>25000</th>
<th>26000</th>
<th>27000</th>
<th>28000</th>
<th>29000</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yield</td>
<td>111.4216</td>
<td>155.0326</td>
<td>181.1176</td>
<td>227.5800</td>
<td>233.4623</td>
<td>242.1753</td>
<td>231.3890</td>
</tr>
</tbody>
</table>
<p>Suppose we wish to determine the linear relationship between per Rate and Yield. We can determine this by solving a system of linear equations, of the form</p>
<p><span class="math display">\[
\begin{aligned}
111.4216 &amp; = \beta_1 + \beta_2 \times 23000 \\
155.0326 &amp; = \beta_1 + \beta_2 \times 24000  \\
\vdots &amp; = \vdots \\
231.3890 &amp; = \beta_1 + \beta_2 \times 29000 \\
\end{aligned}
\]</span></p>
<p>We write this in matrix notation as</p>
<p><span class="math display">\[
\left(\begin{array}{c}
111.4216 \\
155.0326 \\
\vdots \\
231.3890 
 \end{array}\right) 
 =
 \left(\begin{array}{rr}
 1 &amp; 23000 \\
 1 &amp; 24000  \\
\vdots &amp; \vdots \\
 1 &amp; 29000
 \end{array}\right) 
 \left(\begin{array}{c}
 \beta_1 \\
 \beta_2
 \end{array}\right)^t
\]</span></p>
<p>We might write this as</p>
<p><span class="math display">\[
\mathbf{y} = \mathbf{X} \mathbf{\beta}
\]</span></p>
<p>and find a solution by computing <span class="math inline">\(\mathbf{\hat{\beta}} = \mathbf{X}^{- 1}\mathbf{y}\)</span>.</p>
<p>However, an exact solution for the inverse, <span class="math inline">\(\mathbf{X}^{- 1}\)</span> require square matrices, so commonly we use the <em>normal</em> equations,</p>
<p><span class="math display">\[ \mathbf{X}^{t}  \mathbf{y} = \mathbf{X}^{t} \mathbf{X}  \mathbf{\beta} \]</span>
(where <span class="math inline">\(\mathbf{X}^{t}\)</span> is the transpose of <span class="math inline">\(\mathbf{X}\)</span>). We then find <span class="math inline">\(\hat{\mathbf{\beta}} = \mathbf{X}^{t} \mathbf{X} ^{-1} \mathbf{X}^{t} \mathbf{y}\)</span></p>
<div id="answer" class="section level3">
<h3>Answer</h3>
<p>Define appropriate <code>X</code> and <code>y</code> matrices (<code>y</code> can be a vector in R) in the chunk below.</p>
<p>Multiply the transpose of <code>X</code> by <code>X</code>, then use <code>solve</code> (R) or <code>inv</code> (IML) to find the inverse. Multiply this by the product of transpose <code>X</code> and <code>y</code> to find <code>hat.beta</code>.</p>
<p>Print your <code>hat.beta</code>.</p>
<pre class="r"><code>y &lt;- matrix( c(111.4216, 155.0326, 181.1176, 227.5800, 233.4623, 242.1753, 231.3890), byrow = FALSE)
y</code></pre>
<pre><code>##          [,1]
## [1,] 111.4216
## [2,] 155.0326
## [3,] 181.1176
## [4,] 227.5800
## [5,] 233.4623
## [6,] 242.1753
## [7,] 231.3890</code></pre>
<pre class="r"><code>#creating a matrix for bias term
bias=rep(1:1, length.out=length(y))
bias</code></pre>
<pre><code>## [1] 1 1 1 1 1 1 1</code></pre>
<pre class="r"><code>cx &lt;- c(23000, 24000, 25000, 26000 , 27000, 28000, 29000)
X=matrix(c(bias,cx), ncol = 2)
X</code></pre>
<pre><code>##      [,1]  [,2]
## [1,]    1 23000
## [2,]    1 24000
## [3,]    1 25000
## [4,]    1 26000
## [5,]    1 27000
## [6,]    1 28000
## [7,]    1 29000</code></pre>
<pre class="r"><code>#multplication of transpose of x and x
tX=t(X)
tX</code></pre>
<pre><code>##       [,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]
## [1,]     1     1     1     1     1     1     1
## [2,] 23000 24000 25000 26000 27000 28000 29000</code></pre>
<pre class="r"><code>Xm=tX%*%X
Xm</code></pre>
<pre><code>##        [,1]     [,2]
## [1,]      7 1.82e+05
## [2,] 182000 4.76e+09</code></pre>
<pre class="r"><code>A=solve(Xm)

hat.beta=A%*%(tX%*%y)
hat.beta</code></pre>
<pre><code>##                    [,1]
## [1,] -347.1830785714119
## [2,]    0.0209475821429</code></pre>
<p>To check your work, calculate the values predicted by your statistical model. Compute <code>hat.y</code> by multiplying <code>X</code> and <code>hat.beta</code>,
<span class="math display">\[\hat{y} = \mathbf{X}  \hat{\beta}\]</span>
Plot <code>y</code> vs the independent variable (the second column of <code>X</code>) as points, and <code>hat.y</code> vs independent variable as a line, preferably a different colors. The <code>hat.y</code> values should fall a straight line that interpolates <code>y</code> values.</p>
<pre class="r"><code># compute hat.y 
hat.y &lt;- X %*% hat.beta
# plot
plot(X[,2], y, type = &#39;l&#39;, col = &quot;black&quot;)
lines(X[,2], hat.y, col = &quot;blue&quot;)</code></pre>
<p><img src="/achalneupane.github.io/post/firstpost_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>You can also compare your result to the R function (set <code>eval = TRUE</code>).</p>
<pre class="r"><code>summary(lm(y~X))</code></pre>
<pre><code>## 
## Call:
## lm(formula = y ~ X)
## 
## Residuals:
##             1             2             3             4             5 
## -23.189710714  -0.526292857   4.611125000  30.125942857  15.060660714 
##             6             7 
##   2.826078571 -28.907803571 
## 
## Coefficients: (1 not defined because of singularities)
##                    Estimate      Std. Error  t value  Pr(&gt;|t|)   
## (Intercept) -3.47183079e+02  1.11014646e+02 -3.12736 0.0260348 * 
## X1                       NA              NA       NA        NA   
## X2           2.09475821e-02  4.25721732e-03  4.92049 0.0043956 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 22.5270766 on 5 degrees of freedom
## Multiple R-squared:  0.828832727,    Adjusted R-squared:  0.794599272 
## F-statistic: 24.2111915 on 1 and 5 DF,  p-value: 0.00439564802</code></pre>
<p>Based on my calculation the beta estimates are similar to the beta estimates from the liner model</p>
<div id="alternative-methods" class="section level4">
<h4>Alternative methods</h4>
<p>You can also compute <span class="math inline">\(\hat{\beta}\)</span> by passing both <span class="math inline">\(\mathbf{X}^{t} \mathbf{X} ^{-1}\)</span> and
<span class="math inline">\(\mathbf{X}^{t} \mathbf{y}\)</span> as arguments to <code>solve</code>.</p>
<p>Alternatively, you can install the <code>MASS</code> library and use <code>ginv</code> to compute a generalized inverse <span class="math inline">\(\mathbf{X}^{- 1}\)</span>. Use this to compute <span class="math inline">\(\mathbf{\hat{\beta}} = \mathbf{X}^-\mathbf{y}\)</span> in the chunk below:</p>
<pre class="r"><code>library(MASS)</code></pre>
</div>
</div>
</div>
<div id="exercise-6" class="section level1">
<h1>Exercise 6</h1>
<p>Given a vector of mean estimates <span class="math inline">\(x = x_1, x_2, \dots, x_k\)</span>, a vector of standard deviations <span class="math inline">\(s = s_1, s_2, \dots, s_k\)</span> and a vector of sample sizes <span class="math inline">\(n = n_1, n_2, \dots, n_k\)</span>, we can calculate a one-way analysis of variance by</p>
<p><span class="math display">\[
MSB = \frac{n_1(x_1-\bar{x})^2 + n_2(x_2-\bar{x})^2 + \dots + n_k(x_k-\bar{x})^2} {k-1} = \frac{\sum_i n_i(x_i-\bar{x})^2}{k-1}
\]</span>
and</p>
<p><span class="math display">\[
MSW = \frac{(n_1-1)s_1^2 + (n_2-1)s_2^2 + \dots (n_k-1)s_k^2 }{N-k} = \frac{\sum_i (n_i-1)s_i^2}{N-k}
\]</span></p>
<p>where <span class="math inline">\(\bar{x}\)</span> is the mean of <span class="math inline">\(x_i\)</span> and <span class="math inline">\(N = \sum_i n_i\)</span>. The test statistic is <span class="math inline">\(F = \frac{MSB}{MSW}\)</span> which is distributed as <span class="math inline">\(F_{\alpha,k-1,N-k}\)</span></p>
<div id="part-a-1" class="section level3">
<h3>Part a</h3>
<p>Calculate MSW and MSB for Calories per Serving from Wansink Table 1. You can use the variables <code>CaloriesPerServingMean</code> and <code>CaloriesPerServingSD</code> defined below. Let <span class="math inline">\(n_1 = n_2 ... = n_k = 18\)</span></p>
<p>Use array functions and arithmetic for your calculations, you should not need iteration (for loops). Do not hard code values for <span class="math inline">\(N\)</span> and <span class="math inline">\(k\)</span>, calculate these from the <code>CaloriesPerServingMean</code> or <code>CaloriesPerServingSD</code>.</p>
<p>Print both MSB and MSW.</p>
<pre class="r"><code>CaloriesPerServingMean &lt;- c(268.1, 271.1, 280.9, 294.7, 285.6, 288.6, 384.4)
CaloriesPerServingSD &lt;- c(124.8, 124.2, 116.2, 117.7, 118.3, 122.0, 168.3)
#mean for servingperrecipe
mean = mean(CaloriesPerServingMean)
mean</code></pre>
<pre><code>## [1] 296.2</code></pre>
<pre class="r"><code>k &lt;- length(CaloriesPerServingMean)
k</code></pre>
<pre><code>## [1] 7</code></pre>
<pre class="r"><code># We have 18 samples in each year group; so our N is:
n &lt;- rep(18, k)
N &lt;- sum(n)
#calculating MSB 
mean.CaloriesPerServingMean &lt;- mean(CaloriesPerServingMean)
MSB = (sum(n*(CaloriesPerServingMean-mean.CaloriesPerServingMean)^2))/(k-1)
MSB</code></pre>
<pre><code>## [1] 28815.96</code></pre>
<pre class="r"><code>MSW &lt;- sum((n-1) * CaloriesPerServingSD^2)/(N-k)
MSW</code></pre>
<pre><code>## [1] 16508.5985714</code></pre>
</div>
<div id="part-b-1" class="section level3">
<h3>Part b</h3>
<p>Calculate an F-ratio and a <span class="math inline">\(p\)</span> for this <span class="math inline">\(F\)</span>, using the <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(k-1\)</span> and <span class="math inline">\(N-k\)</span> degrees of freedom. Use <span class="math inline">\(\alpha = 0.05\)</span>. Compare these values to the corresponding values reported in Wansink Table 1.</p>
<pre class="r"><code># Calculating F.ratio
F.ratio &lt;- MSB/MSW
df1 &lt;- k-1
df2 &lt;- N-k
p.value &lt;- pf(F.ratio, df1, df2, lower.tail = FALSE)
p.value</code></pre>
<pre><code>## [1] 0.116313264501</code></pre>
<p>You can check your results by entering appropriate values in an online calculator like <a href="http://statpages.info/anova1sm.html" class="uri">http://statpages.info/anova1sm.html</a> .</p>
<p>Group Name N(count) Mean Std.Dev
Group1 18 268.1 124.8
Group2 18 271.1 124.2
Group3 18 280.9 116.2
.
.
.
Group7 18 384.4 168.3</p>
<p>Then set Desired confidence level for post-hoc confidence intervals: 5</p>
<p>Finally, cross-check your answers!</p>
</div>
</div>

    </div>

    


    

<div class="article-tags">
  
  <a class="badge badge-light" href="/achalneupane.github.io/tags/statistics/">Statistics</a>
  
</div>



    
      








  





  
  
  
    
  
  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    
      
      <img class="portrait mr-3" src="/achalneupane.github.io/authors/admin/avatar_hub87dad2c2f49da0df2a3614534a2c7e2_76844_250x250_fill_q90_lanczos_center.jpg" itemprop="image" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/achalneupane.github.io/">Achal Neupane</a></h5>
      
      
      <ul class="network-icon" aria-hidden="true">
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="/achalneupane.github.io/#contact" >
              <i class="fas fa-envelope"></i>
            </a>
          </li>
        
          
          
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://scholar.google.com/citations?user=p1ky6LcAAAAJ&amp;hl=en" target="_blank" rel="noopener">
              <i class="ai ai-google-scholar"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://github.com/achalneupane" target="_blank" rel="noopener">
              <i class="fab fa-github"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://stackoverflow.com/users/4701887/mapk" target="_blank" rel="noopener">
              <i class="fab fa-stack-overflow"></i>
            </a>
          </li>
        
          
          
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://www.researchgate.net/profile/An_An34" target="_blank" rel="noopener">
              <i class="ai ai-researchgate"></i>
            </a>
          </li>
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/achalneupane.github.io/post/arrays/">Arrays</a></li>
          
        </ul>
      </div>
      
    

    

    


  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
    

    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/achalneupane.github.io/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/achalneupane.github.io/js/academic.min.16bbb3750feb7244c9bc409a5a4fe678.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/achalneupane.github.io/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/achalneupane.github.io/terms/">Terms</a>
        
  </p>
  

  <p class="powered-by">
    &copy; 2019 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
